<?php
use xz1mefx\multilang\models\Language;
use xz1mefx\multilang\models\Message;
use xz1mefx\multilang\models\SourceMessage;
use yii\db\Migration;

class m161210_131014_multilang_init extends Migration
{

    public function up()
    {
        $this->down();

        $tableOptions = NULL;
        if ($this->db->driverName === 'mysql') {
            // http://stackoverflow.com/questions/766809/whats-the-difference-between-utf8-general-ci-and-utf8-unicode-ci
            $tableOptions = 'CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE=InnoDB';
        }


        // -------------------------------------------
        // Create langs tables
        // -------------------------------------------

        // Language table
        $this->createTable(Language::TABLE_NAME, [
            'id' => $this->primaryKey()->unsigned(),
            'url' => $this->string(2)->notNull()->unique(),
            'locale' => $this->string(16)->notNull()->unique(),
            'name' => $this->string()->notNull(),
            'default' => $this->smallInteger(1)->notNull()->defaultValue(0),

            'created_at' => $this->integer()->unsigned()->notNull()->defaultValue(0),
            'updated_at' => $this->integer()->unsigned()->notNull()->defaultValue(0),
        ], $tableOptions);

        // Add default languages
        $this->insert(Language::TABLE_NAME, [
            'url' => 'ru',
            'locale' => 'ru-RU',
            'name' => 'Русский',
            'created_at' => time(),
            'updated_at' => time(),
        ]);
        $this->insert(Language::TABLE_NAME, [
            'url' => 'uk',
            'locale' => 'uk-UA',
            'name' => 'Українська',
            'created_at' => time(),
            'updated_at' => time(),
        ]);
        $this->insert(Language::TABLE_NAME, [
            'url' => 'en',
            'locale' => 'en-US',
            'name' => 'English',
            'default' => 1,
            'created_at' => time(),
            'updated_at' => time(),
        ]);

        // Add translate tables
        $this->createTable(SourceMessage::TABLE_NAME, [
            'id' => $this->primaryKey()->unsigned(),
            'category' => $this->string(32),
            'message' => $this->text()->notNull(),

            'created_at' => $this->integer()->unsigned()->notNull()->defaultValue(0),
            'updated_at' => $this->integer()->unsigned()->notNull()->defaultValue(0),
        ], $tableOptions);
        $this->createTable(Message::TABLE_NAME, [
            'id' => $this->integer()->unsigned(),
            'language' => $this->string(16),
            'translation' => $this->text(),

            'created_at' => $this->integer()->unsigned()->notNull()->defaultValue(0),
            'updated_at' => $this->integer()->unsigned()->notNull()->defaultValue(0),
        ], $tableOptions);

        $this->createIndex('message_id_language', Message::TABLE_NAME, ['id', 'language'], TRUE);
        $this->addForeignKey('fk_message_source_message', Message::TABLE_NAME, 'id', SourceMessage::TABLE_NAME, 'id', 'CASCADE', 'CASCADE');


        // -------------------------------------------
        // Update translates tables
        // -------------------------------------------

        $this->setTranslates();
    }

    public function down()
    {
        Yii::$app->multilangCache->flush();
        if (Yii::$app->db->schema->getTableSchema(Message::TABLE_NAME) !== NULL) {
            $this->dropTable(Message::TABLE_NAME);
        }
        if (Yii::$app->db->schema->getTableSchema(SourceMessage::TABLE_NAME) !== NULL) {
            $this->dropTable(SourceMessage::TABLE_NAME);
        }
        if (Yii::$app->db->schema->getTableSchema(Language::TABLE_NAME) !== NULL) {
            $this->dropTable(Language::TABLE_NAME);
        }
    }

    private function setTranslates()
    {
        $sourceMessageTable = SourceMessage::TABLE_NAME;
        $messageTable = Message::TABLE_NAME;
        $time = time();

        // truncate tables
        $this->execute(<<<SQL
SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE $sourceMessageTable;
TRUNCATE $messageTable;
SET FOREIGN_KEY_CHECKS = 1;
SQL
        );

        // insert default source messages
        $this->execute(<<<SQL
INSERT INTO {$sourceMessageTable} (`id`, `category`, `message`, `created_at`, `updated_at`) VALUES
    (1, 'yii', 'Home', $time, $time),
    (2, 'yii', 'No results found.', $time, $time),
    (3, 'yii', 'Showing <b>{begin, number}-{end, number}</b> of <b>{totalCount, number}</b> {totalCount, plural, one{item} other{items}}.', $time, $time),
    (4, 'yii', 'Total <b>{count, number}</b> {count, plural, one{item} other{items}}.', $time, $time),
    (5, 'yii', 'Unknown alias: -{name}', $time, $time),
    (6, 'yii', 'Unknown option: --{name}', $time, $time),
    (7, 'yii', 'Missing required arguments: {params}', $time, $time),
    (8, 'yii', 'No', $time, $time),
    (9, 'yii', 'Yes', $time, $time),
    (10, 'yii', '(not set)', $time, $time),
    (11, 'yii', 'in {delta, plural, =1{a year} other{# years}}', $time, $time),
    (12, 'yii', 'in {delta, plural, =1{a month} other{# months}}', $time, $time),
    (13, 'yii', 'in {delta, plural, =1{a day} other{# days}}', $time, $time),
    (14, 'yii', 'in {delta, plural, =1{an hour} other{# hours}}', $time, $time),
    (15, 'yii', 'in {delta, plural, =1{a minute} other{# minutes}}', $time, $time),
    (16, 'yii', 'just now', $time, $time),
    (17, 'yii', 'in {delta, plural, =1{a second} other{# seconds}}', $time, $time),
    (18, 'yii', '{delta, plural, =1{a year} other{# years}} ago', $time, $time),
    (19, 'yii', '{delta, plural, =1{a month} other{# months}} ago', $time, $time),
    (20, 'yii', '{delta, plural, =1{a day} other{# days}} ago', $time, $time),
    (21, 'yii', '{delta, plural, =1{an hour} other{# hours}} ago', $time, $time),
    (22, 'yii', '{delta, plural, =1{a minute} other{# minutes}} ago', $time, $time),
    (23, 'yii', '{delta, plural, =1{a second} other{# seconds}} ago', $time, $time),
    (24, 'yii', '{delta, plural, =1{1 year} other{# years}}', $time, $time),
    (25, 'yii', '{delta, plural, =1{1 month} other{# months}}', $time, $time),
    (26, 'yii', '{delta, plural, =1{1 day} other{# days}}', $time, $time),
    (27, 'yii', '{delta, plural, =1{1 hour} other{# hours}}', $time, $time),
    (28, 'yii', '{delta, plural, =1{1 minute} other{# minutes}}', $time, $time),
    (29, 'yii', '{delta, plural, =1{1 second} other{# seconds}}', $time, $time),
    (30, 'yii', '{nFormatted} B', $time, $time),
    (31, 'yii', '{nFormatted} KiB', $time, $time),
    (32, 'yii', '{nFormatted} MiB', $time, $time),
    (33, 'yii', '{nFormatted} GiB', $time, $time),
    (34, 'yii', '{nFormatted} TiB', $time, $time),
    (35, 'yii', '{nFormatted} PiB', $time, $time),
    (36, 'yii', '{nFormatted} KB', $time, $time),
    (37, 'yii', '{nFormatted} MB', $time, $time),
    (38, 'yii', '{nFormatted} GB', $time, $time),
    (39, 'yii', '{nFormatted} TB', $time, $time),
    (40, 'yii', '{nFormatted} PB', $time, $time),
    (41, 'yii', '{nFormatted} {n, plural, =1{byte} other{bytes}}', $time, $time),
    (42, 'yii', '{nFormatted} {n, plural, =1{kibibyte} other{kibibytes}}', $time, $time),
    (43, 'yii', '{nFormatted} {n, plural, =1{mebibyte} other{mebibytes}}', $time, $time),
    (44, 'yii', '{nFormatted} {n, plural, =1{gibibyte} other{gibibytes}}', $time, $time),
    (45, 'yii', '{nFormatted} {n, plural, =1{tebibyte} other{tebibytes}}', $time, $time),
    (46, 'yii', '{nFormatted} {n, plural, =1{pebibyte} other{pebibytes}}', $time, $time),
    (47, 'yii', '{nFormatted} {n, plural, =1{kilobyte} other{kilobytes}}', $time, $time),
    (48, 'yii', '{nFormatted} {n, plural, =1{megabyte} other{megabytes}}', $time, $time),
    (49, 'yii', '{nFormatted} {n, plural, =1{gigabyte} other{gigabytes}}', $time, $time),
    (50, 'yii', '{nFormatted} {n, plural, =1{terabyte} other{terabytes}}', $time, $time),
    (51, 'yii', '{nFormatted} {n, plural, =1{petabyte} other{petabytes}}', $time, $time),
    (52, 'yii', 'You are not allowed to perform this action.', $time, $time),
    (53, 'yii', 'Powered by {yii}', $time, $time),
    (54, 'yii', 'Yii Framework', $time, $time),
    (55, 'yii', 'Page not found.', $time, $time),
    (56, 'yii', 'Error', $time, $time),
    (57, 'yii', 'An internal server error occurred.', $time, $time),
    (58, 'yii', 'Login Required', $time, $time),
    (59, 'yii', 'The requested view "{name}" was not found.', $time, $time),
    (60, 'yii', 'Invalid data received for parameter "{param}".', $time, $time),
    (61, 'yii', 'Missing required parameters: {params}', $time, $time),
    (62, 'yii', 'Unable to verify your data submission.', $time, $time),
    (63, 'yii', '{attribute} is invalid.', $time, $time),
    (64, 'yii', 'The combination {values} of {attributes} has already been taken.', $time, $time),
    (65, 'yii', '{attribute} "{value}" has already been taken.', $time, $time),
    (66, 'yii', 'File upload failed.', $time, $time),
    (67, 'yii', 'Please upload a file.', $time, $time),
    (68, 'yii', 'You can upload at most {limit, number} {limit, plural, one{file} other{files}}.', $time, $time),
    (69, 'yii', 'Only files with these extensions are allowed: {extensions}.', $time, $time),
    (70, 'yii', 'The file "{file}" is too big. Its size cannot exceed {formattedLimit}.', $time, $time),
    (71, 'yii', 'The file "{file}" is too small. Its size cannot be smaller than {formattedLimit}.', $time, $time),
    (72, 'yii', 'Only files with these MIME types are allowed: {mimeTypes}.', $time, $time),
    (73, 'yii', 'The format of {attribute} is invalid.', $time, $time),
    (74, 'yii', '{attribute} must be no less than {min}.', $time, $time),
    (75, 'yii', '{attribute} must be no greater than {max}.', $time, $time),
    (76, 'yii', '{attribute} must be equal to "{compareValueOrAttribute}".', $time, $time),
    (77, 'yii', '{attribute} must not be equal to "{compareValueOrAttribute}".', $time, $time),
    (78, 'yii', '{attribute} must be greater than "{compareValueOrAttribute}".', $time, $time),
    (79, 'yii', '{attribute} must be greater than or equal to "{compareValueOrAttribute}".', $time, $time),
    (80, 'yii', '{attribute} must be less than "{compareValueOrAttribute}".', $time, $time),
    (81, 'yii', '{attribute} must be less than or equal to "{compareValueOrAttribute}".', $time, $time),
    (82, 'yii', 'the input value', $time, $time),
    (83, 'yii', '{attribute} must be a string.', $time, $time),
    (84, 'yii', '{attribute} should contain at least {min, number} {min, plural, one{character} other{characters}}.', $time, $time),
    (85, 'yii', '{attribute} should contain at most {max, number} {max, plural, one{character} other{characters}}.', $time, $time),
    (86, 'yii', '{attribute} should contain {length, number} {length, plural, one{character} other{characters}}.', $time, $time),
    (87, 'yii', '{attribute} must be an integer.', $time, $time),
    (88, 'yii', '{attribute} must be a number.', $time, $time),
    (89, 'yii', '{attribute} must be either "{true}" or "{false}".', $time, $time),
    (90, 'yii', '{attribute} is not a valid email address.', $time, $time),
    (91, 'yii', '{attribute} is not a valid URL.', $time, $time),
    (92, 'yii', '{attribute} cannot be blank.', $time, $time),
    (93, 'yii', '{attribute} must be "{requiredValue}".', $time, $time),
    (94, 'yii', 'The file "{file}" is not an image.', $time, $time),
    (95, 'yii', 'The image "{file}" is too small. The width cannot be smaller than {limit, number} {limit, plural, one{pixel} other{pixels}}.', $time, $time),
    (96, 'yii', 'The image "{file}" is too small. The height cannot be smaller than {limit, number} {limit, plural, one{pixel} other{pixels}}.', $time, $time),
    (97, 'yii', 'The image "{file}" is too large. The width cannot be larger than {limit, number} {limit, plural, one{pixel} other{pixels}}.', $time, $time),
    (98, 'yii', 'The image "{file}" is too large. The height cannot be larger than {limit, number} {limit, plural, one{pixel} other{pixels}}.', $time, $time),
    (99, 'yii', '{attribute} must be a valid IP address.', $time, $time),
    (100, 'yii', '{attribute} must not be an IPv6 address.', $time, $time),
    (101, 'yii', '{attribute} must not be an IPv4 address.', $time, $time),
    (102, 'yii', '{attribute} contains wrong subnet mask.', $time, $time),
    (103, 'yii', '{attribute} must be an IP address with specified subnet.', $time, $time),
    (104, 'yii', '{attribute} must not be a subnet.', $time, $time),
    (105, 'yii', '{attribute} is not in the allowed range.', $time, $time),
    (106, 'yii', 'The verification code is incorrect.', $time, $time),
    (107, 'yii', 'View', $time, $time),
    (108, 'yii', 'Update', $time, $time),
    (109, 'yii', 'Delete', $time, $time),
    (110, 'yii', 'Are you sure you want to delete this item?', $time, $time),
    (111, 'yii', 'Please fix the following errors:', $time, $time),
    (112, 'yii', '{percent}% Complete', $time, $time),
    (113, 'multilang-tools', 'Update translation', $time, $time),
    (114, 'multilang-tools', 'Interface translations', $time, $time),
    (115, 'multilang-tools', 'Create', $time, $time),
    (116, 'multilang-tools', 'Update', $time, $time),
    (117, 'multilang-tools', 'Translation ({language})', $time, $time),
    (118, 'multilang-tools', 'Add language', $time, $time),
    (119, 'multilang-tools', 'Languages', $time, $time),
    (120, 'multilang-tools', 'Update language:', $time, $time),
    (121, 'multilang-tools', 'If you select this option here, it will be reset everywhere', $time, $time),
    (122, 'multilang-tools', 'Update language', $time, $time),
    (123, 'multilang-tools', 'The combination of ID and Language has already been taken.', $time, $time),
    (124, 'multilang-tools', 'ID', $time, $time),
    (125, 'multilang-tools', 'Language', $time, $time),
    (126, 'multilang-tools', 'Translation', $time, $time),
    (127, 'multilang-tools', 'You can only override the default language', $time, $time),
    (128, 'multilang-tools', 'Url (ISO 639-1)', $time, $time),
    (129, 'multilang-tools', 'Locale', $time, $time),
    (130, 'multilang-tools', 'Name', $time, $time),
    (131, 'multilang-tools', 'Is Default', $time, $time),
    (132, 'multilang-tools', 'Created At', $time, $time),
    (133, 'multilang-tools', 'Updated At', $time, $time),
    (134, 'multilang-tools', 'Message category', $time, $time),
    (135, 'multilang-tools', 'Message key', $time, $time),
    (136, 'multilang-tools', 'The requested translation does not exist', $time, $time),
    (137, 'multilang-tools', 'Translation updated successfully!', $time, $time),
    (138, 'multilang-tools', 'The requested language does not exist', $time, $time),
    (139, 'multilang-tools', 'You can''t delete default language!', $time, $time),
    (140, 'multilang-tools', 'Language deleted successfully!', $time, $time),
    (141, 'multilang-tools', 'Language updated successfully!', $time, $time),
    (142, 'multilang-tools', 'Language created successfully!', $time, $time),
    (143, 'multilang-tools', 'Русский', $time, $time),
    (144, 'multilang-tools', 'Українська', $time, $time),
    (145, 'multilang-tools', 'English', $time, $time),
    (146, 'multilang-tools', 'Enter a url...', $time, $time),
    (147, 'multilang-tools', 'Enter a locale...', $time, $time),
    (148, 'multilang-tools', 'Enter a name...', $time, $time),
    (149, 'multilang-tools', 'Enter a translate...', $time, $time);
SQL
        );

        // Insert default messages
        $this->execute(<<<SQL
INSERT INTO {$messageTable} (`id`, `language`, `translation`, `created_at`, `updated_at`) VALUES
    (1, 'en-US', 'Home', $time, $time),
    (1, 'ru-RU', 'Главная', $time, $time),
    (1, 'uk-UA', 'Головна', $time, $time),
    (2, 'en-US', 'No results found.', $time, $time),
    (2, 'ru-RU', 'Ничего не найдено.', $time, $time),
    (2, 'uk-UA', 'Нічого не знайдено.', $time, $time),
    (3, 'en-US', 'Showing <b>{begin, number}-{end, number}</b> of <b>{totalCount, number}</b> {totalCount, plural, one{item} other{items}}.', $time, $time),
    (3, 'ru-RU', 'Показаны записи <b>{begin, number}-{end, number}</b> из <b>{totalCount, number}</b>.', $time, $time),
    (3, 'uk-UA', 'Показані <b>{begin, number}-{end, number}</b> із <b>{totalCount, number}</b> {totalCount, plural, one{запису} other{записів}}.', $time, $time),
    (4, 'en-US', 'Total <b>{count, number}</b> {count, plural, one{item} other{items}}.', $time, $time),
    (4, 'ru-RU', 'Всего <b>{count, number}</b> {count, plural, one{запись} few{записи} many{записей} other{записи}}.', $time, $time),
    (4, 'uk-UA', 'Всього <b>{count, number}</b> {count, plural, one{запис} few{записи} many{записів} other{записи}}.', $time, $time),
    (5, 'en-US', 'Unknown alias: -{name}', $time, $time),
    (5, 'ru-RU', 'Unknown alias: -{name}', $time, $time),
    (5, 'uk-UA', 'Unknown alias: -{name}', $time, $time),
    (6, 'en-US', 'Unknown option: --{name}', $time, $time),
    (6, 'ru-RU', 'Неизвестная опция: --{name}', $time, $time),
    (6, 'uk-UA', 'Невідома опція : --{name}', $time, $time),
    (7, 'en-US', 'Missing required arguments: {params}', $time, $time),
    (7, 'ru-RU', 'Отсутствуют обязательные аргументы: {params}', $time, $time),
    (7, 'uk-UA', 'Відсутні обовʼязкові аргументи: {params}', $time, $time),
    (8, 'en-US', 'No', $time, $time),
    (8, 'ru-RU', 'Нет', $time, $time),
    (8, 'uk-UA', 'Ні', $time, $time),
    (9, 'en-US', 'Yes', $time, $time),
    (9, 'ru-RU', 'Да', $time, $time),
    (9, 'uk-UA', 'Так', $time, $time),
    (10, 'en-US', '(not set)', $time, $time),
    (10, 'ru-RU', '(не задано)', $time, $time),
    (10, 'uk-UA', '(не задано)', $time, $time),
    (11, 'en-US', 'in {delta, plural, =1{a year} other{# years}}', $time, $time),
    (11, 'ru-RU', 'через {delta, plural, =1{год} one{# год} few{# года} many{# лет} other{# года}}', $time, $time),
    (11, 'uk-UA', 'через {delta, plural, =1{рік} one{# рік} few{# роки} many{# років} other{# роки}}', $time, $time),
    (12, 'en-US', 'in {delta, plural, =1{a month} other{# months}}', $time, $time),
    (12, 'ru-RU', 'через {delta, plural, =1{месяц} one{# месяц} few{# месяца} many{# месяцев} other{# месяца}}', $time, $time),
    (12, 'uk-UA', 'через {delta, plural, =1{місяць} one{# місяць} few{# місяці} many{# місяців} other{# місяці}}', $time, $time),
    (13, 'en-US', 'in {delta, plural, =1{a day} other{# days}}', $time, $time),
    (13, 'ru-RU', 'через {delta, plural, =1{день} one{# день} few{# дня} many{# дней} other{# дня}}', $time, $time),
    (13, 'uk-UA', 'через {delta, plural, =1{день} one{# день} few{# дні} many{# днів} other{# дні}}', $time, $time),
    (14, 'en-US', 'in {delta, plural, =1{an hour} other{# hours}}', $time, $time),
    (14, 'ru-RU', 'через {delta, plural, =1{час} one{# час} few{# часа} many{# часов} other{# часа}}', $time, $time),
    (14, 'uk-UA', 'через {delta, plural, =1{годину} one{# годину} few{# години} many{# годин} other{# години}}', $time, $time),
    (15, 'en-US', 'in {delta, plural, =1{a minute} other{# minutes}}', $time, $time),
    (15, 'ru-RU', 'через {delta, plural, =1{минуту} one{# минуту} few{# минуты} many{# минут} other{# минуты}}', $time, $time),
    (15, 'uk-UA', 'через {delta, plural, =1{хвилину} one{# хвилину} few{# хвилини} many{# хвилин} other{# хвилини}}', $time, $time),
    (16, 'en-US', 'just now', $time, $time),
    (16, 'ru-RU', 'прямо сейчас', $time, $time),
    (16, 'uk-UA', 'саме зараз', $time, $time),
    (17, 'en-US', 'in {delta, plural, =1{a second} other{# seconds}}', $time, $time),
    (17, 'ru-RU', 'через {delta, plural, =1{секунду} one{# секунду} few{# секунды} many{# секунд} other{# секунды}}', $time, $time),
    (17, 'uk-UA', 'через {delta, plural, =1{секунду} one{# секунду} few{# секунди} many{# секунд} other{# секунди}}', $time, $time),
    (18, 'en-US', '{delta, plural, =1{a year} other{# years}} ago', $time, $time),
    (18, 'ru-RU', '{delta, plural, =1{год} one{# год} few{# года} many{# лет} other{# года}} назад', $time, $time),
    (18, 'uk-UA', '{delta, plural, =1{рік} one{# рік} few{# роки} many{# років} other{# роки}} тому', $time, $time),
    (19, 'en-US', '{delta, plural, =1{a month} other{# months}} ago', $time, $time),
    (19, 'ru-RU', '{delta, plural, =1{месяц} one{# месяц} few{# месяца} many{# месяцев} other{# месяца}} назад', $time, $time),
    (19, 'uk-UA', '{delta, plural, =1{місяць} one{# місяць} few{# місяці} many{# місяців} other{# місяці}} тому', $time, $time),
    (20, 'en-US', '{delta, plural, =1{a day} other{# days}} ago', $time, $time),
    (20, 'ru-RU', '{delta, plural, =1{день} one{# день} few{# дня} many{# дней} other{# дня}} назад', $time, $time),
    (20, 'uk-UA', '{delta, plural, =1{день} one{# день} few{# дні} many{# днів} other{# дні}} тому', $time, $time),
    (21, 'en-US', '{delta, plural, =1{an hour} other{# hours}} ago', $time, $time),
    (21, 'ru-RU', '{delta, plural, =1{час} one{# час} few{# часа} many{# часов} other{# часа}} назад', $time, $time),
    (21, 'uk-UA', '{delta, plural, =1{година} one{# година} few{# години} many{# годин} other{# години}} тому', $time, $time),
    (22, 'en-US', '{delta, plural, =1{a minute} other{# minutes}} ago', $time, $time),
    (22, 'ru-RU', '{delta, plural, =1{минуту} one{# минуту} few{# минуты} many{# минут} other{# минуты}} назад', $time, $time),
    (22, 'uk-UA', '{delta, plural, =1{хвилину} one{# хвилину} few{# хвилини} many{# хвилин} other{# хвилини}} тому', $time, $time),
    (23, 'en-US', '{delta, plural, =1{a second} other{# seconds}} ago', $time, $time),
    (23, 'ru-RU', '{delta, plural, =1{секунду} one{# секунду} few{# секунды} many{# секунд} other{# секунды}} назад', $time, $time),
    (23, 'uk-UA', '{delta, plural, =1{секунду} one{# секунду} few{# секунди} many{# секунд} other{# секунди}} тому', $time, $time),
    (24, 'en-US', '{delta, plural, =1{1 year} other{# years}}', $time, $time),
    (24, 'ru-RU', '{delta, plural, one{# год} few{# года} many{# лет} other{# лет}}', $time, $time),
    (24, 'uk-UA', '{delta, plural, one{# рік} few{# роки} many{# років} other{# років}}', $time, $time),
    (25, 'en-US', '{delta, plural, =1{1 month} other{# months}}', $time, $time),
    (25, 'ru-RU', '{delta, plural, one{# месяц} few{# месяца} many{# месяцев} other{# месяцев}}', $time, $time),
    (25, 'uk-UA', '{delta, plural, one{# місяць} few{# місяця} many{# місяців} other{# місяців}}', $time, $time),
    (26, 'en-US', '{delta, plural, =1{1 day} other{# days}}', $time, $time),
    (26, 'ru-RU', '{delta, plural, one{# день} few{# дня} many{# дней} other{# дней}}', $time, $time),
    (26, 'uk-UA', '{delta, plural, one{# день} few{# дні} many{# днів} other{# днів}}', $time, $time),
    (27, 'en-US', '{delta, plural, =1{1 hour} other{# hours}}', $time, $time),
    (27, 'ru-RU', '{delta, plural, one{# час} few{# часа} many{# часов} other{# часов}}', $time, $time),
    (27, 'uk-UA', '{delta, plural, one{# година} few{# години} many{# годин} other{# годин}}', $time, $time),
    (28, 'en-US', '{delta, plural, =1{1 minute} other{# minutes}}', $time, $time),
    (28, 'ru-RU', '{delta, plural, one{# минута} few{# минуты} many{# минут} other{# минут}}', $time, $time),
    (28, 'uk-UA', '{delta, plural, one{# хвилина} few{# хвилини} many{# хвилин} other{# хвилин}}', $time, $time),
    (29, 'en-US', '{delta, plural, =1{1 second} other{# seconds}}', $time, $time),
    (29, 'ru-RU', '{delta, plural, one{# секунда} few{# секунды} many{# секунд} other{# секунд}}', $time, $time),
    (29, 'uk-UA', '{delta, plural, one{# секунда} few{# секунди} many{# секунд} other{# секунд}}', $time, $time),
    (30, 'en-US', '{nFormatted} B', $time, $time),
    (30, 'ru-RU', '{nFormatted} Б', $time, $time),
    (30, 'uk-UA', '{nFormatted} Б', $time, $time),
    (31, 'en-US', '{nFormatted} KiB', $time, $time),
    (31, 'ru-RU', '{nFormatted} КиБ', $time, $time),
    (31, 'uk-UA', '{nFormatted} КіБ', $time, $time),
    (32, 'en-US', '{nFormatted} MiB', $time, $time),
    (32, 'ru-RU', '{nFormatted} МиБ', $time, $time),
    (32, 'uk-UA', '{nFormatted} МіБ', $time, $time),
    (33, 'en-US', '{nFormatted} GiB', $time, $time),
    (33, 'ru-RU', '{nFormatted} ГиБ', $time, $time),
    (33, 'uk-UA', '{nFormatted} ГіБ', $time, $time),
    (34, 'en-US', '{nFormatted} TiB', $time, $time),
    (34, 'ru-RU', '{nFormatted} ТиБ', $time, $time),
    (34, 'uk-UA', '{nFormatted} ТіБ', $time, $time),
    (35, 'en-US', '{nFormatted} PiB', $time, $time),
    (35, 'ru-RU', '{nFormatted} ПиБ', $time, $time),
    (35, 'uk-UA', '{nFormatted} ПіБ', $time, $time),
    (36, 'en-US', '{nFormatted} KB', $time, $time),
    (36, 'ru-RU', '{nFormatted} КБ', $time, $time),
    (36, 'uk-UA', '{nFormatted} Кб', $time, $time),
    (37, 'en-US', '{nFormatted} MB', $time, $time),
    (37, 'ru-RU', '{nFormatted} МБ', $time, $time),
    (37, 'uk-UA', '{nFormatted} Мб', $time, $time),
    (38, 'en-US', '{nFormatted} GB', $time, $time),
    (38, 'ru-RU', '{nFormatted} ГБ', $time, $time),
    (38, 'uk-UA', '{nFormatted} Гб', $time, $time),
    (39, 'en-US', '{nFormatted} TB', $time, $time),
    (39, 'ru-RU', '{nFormatted} ТБ', $time, $time),
    (39, 'uk-UA', '{nFormatted} Тб', $time, $time),
    (40, 'en-US', '{nFormatted} PB', $time, $time),
    (40, 'ru-RU', '{nFormatted} ПБ', $time, $time),
    (40, 'uk-UA', '{nFormatted} Пб', $time, $time),
    (41, 'en-US', '{nFormatted} {n, plural, =1{byte} other{bytes}}', $time, $time),
    (41, 'ru-RU', '{nFormatted} {n, plural, one{байт} few{байта} many{байтов} other{байта}}', $time, $time),
    (41, 'uk-UA', '{nFormatted} {n, plural, one{байт} few{байта} many{байтів} other{байта}}', $time, $time),
    (42, 'en-US', '{nFormatted} {n, plural, =1{kibibyte} other{kibibytes}}', $time, $time),
    (42, 'ru-RU', '{nFormatted} {n, plural, one{кибибайт} few{кибибайта} many{кибибайтов} other{кибибайта}}', $time, $time),
    (42, 'uk-UA', '{nFormatted} {n, plural, one{кібібайт} few{кібібайта} many{кібібайтів} other{кібібайта}}', $time, $time),
    (43, 'en-US', '{nFormatted} {n, plural, =1{mebibyte} other{mebibytes}}', $time, $time),
    (43, 'ru-RU', '{nFormatted} {n, plural, one{мебибайт} few{мебибайта} many{мебибайтов} other{мебибайта}}', $time, $time),
    (43, 'uk-UA', '{nFormatted} {n, plural, one{мебібайт} few{мебібайта} many{мебібайтів} other{мебібайта}}', $time, $time),
    (44, 'en-US', '{nFormatted} {n, plural, =1{gibibyte} other{gibibytes}}', $time, $time),
    (44, 'ru-RU', '{nFormatted} {n, plural, one{гибибайт} few{гибибайта} many{гибибайтов} other{гибибайта}}', $time, $time),
    (44, 'uk-UA', '{nFormatted} {n, plural, one{гібібайт} few{гібібайта} many{гібібайтів} other{гібібайта}}', $time, $time),
    (45, 'en-US', '{nFormatted} {n, plural, =1{tebibyte} other{tebibytes}}', $time, $time),
    (45, 'ru-RU', '{nFormatted} {n, plural, one{тебибайт} few{тебибайта} many{тебибайтов} other{тебибайта}}', $time, $time),
    (45, 'uk-UA', '{nFormatted} {n, plural, one{тебібайт} few{тебібайта} many{тебібайтів} other{тебібайта}}', $time, $time),
    (46, 'en-US', '{nFormatted} {n, plural, =1{pebibyte} other{pebibytes}}', $time, $time),
    (46, 'ru-RU', '{nFormatted} {n, plural, one{пебибайт} few{пебибайта} many{пебибайтов} other{пебибайта}}', $time, $time),
    (46, 'uk-UA', '{nFormatted} {n, plural, one{пебібайт} few{пебібайта} many{пебібайтів} other{пебібайта}}', $time, $time),
    (47, 'en-US', '{nFormatted} {n, plural, =1{kilobyte} other{kilobytes}}', $time, $time),
    (47, 'ru-RU', '{nFormatted} {n, plural, one{килобайт} few{килобайта} many{килобайтов} other{килобайта}}', $time, $time),
    (47, 'uk-UA', '{nFormatted} {n, plural, one{кілобайт} few{кілобайта} many{кілобайтів} other{кілобайта}}', $time, $time),
    (48, 'en-US', '{nFormatted} {n, plural, =1{megabyte} other{megabytes}}', $time, $time),
    (48, 'ru-RU', '{nFormatted} {n, plural, one{мегабайт} few{мегабайта} many{мегабайтов} other{мегабайта}}', $time, $time),
    (48, 'uk-UA', '{nFormatted} {n, plural, one{мегабайт} few{мегабайта} many{мегабайтів} other{мегабайта}}', $time, $time),
    (49, 'en-US', '{nFormatted} {n, plural, =1{gigabyte} other{gigabytes}}', $time, $time),
    (49, 'ru-RU', '{nFormatted} {n, plural, one{гигабайт} few{гигабайта} many{гигабайтов} other{гигабайта}}', $time, $time),
    (49, 'uk-UA', '{nFormatted} {n, plural, one{гігабайт} few{гігабайта} many{гігабайтів} other{гігабайта}}', $time, $time),
    (50, 'en-US', '{nFormatted} {n, plural, =1{terabyte} other{terabytes}}', $time, $time),
    (50, 'ru-RU', '{nFormatted} {n, plural, one{терабайт} few{терабайта} many{терабайтов} other{терабайта}}', $time, $time),
    (50, 'uk-UA', '{nFormatted} {n, plural, one{терабайт} few{терабайта} many{терабайтів} other{терабайта}}', $time, $time),
    (51, 'en-US', '{nFormatted} {n, plural, =1{petabyte} other{petabytes}}', $time, $time),
    (51, 'ru-RU', '{nFormatted} {n, plural, one{петабайт} few{петабайта} many{петабайтов} other{петабайта}}', $time, $time),
    (51, 'uk-UA', '{nFormatted} {n, plural, one{петабайт} few{петабайта} many{петабайтів} other{петабайта}}', $time, $time),
    (52, 'en-US', 'You are not allowed to perform this action.', $time, $time),
    (52, 'ru-RU', 'Вам не разрешено производить данное действие.', $time, $time),
    (52, 'uk-UA', 'Вам не дозволено виконувати дану дію.', $time, $time),
    (53, 'en-US', 'Powered by {yii}', $time, $time),
    (53, 'ru-RU', 'Powered by {yii}', $time, $time),
    (53, 'uk-UA', 'Powered by {yii}', $time, $time),
    (54, 'en-US', 'Yii Framework', $time, $time),
    (54, 'ru-RU', 'Yii Framework', $time, $time),
    (54, 'uk-UA', 'Yii Framework', $time, $time),
    (55, 'en-US', 'Page not found.', $time, $time),
    (55, 'ru-RU', 'Страница не найдена.', $time, $time),
    (55, 'uk-UA', 'Сторінка не знайдена.', $time, $time),
    (56, 'en-US', 'Error', $time, $time),
    (56, 'ru-RU', 'Ошибка', $time, $time),
    (56, 'uk-UA', 'Помилка', $time, $time),
    (57, 'en-US', 'An internal server error occurred.', $time, $time),
    (57, 'ru-RU', 'Возникла внутренняя ошибка сервера.', $time, $time),
    (57, 'uk-UA', 'Виникла внутрішня помилка сервера.', $time, $time),
    (58, 'en-US', 'Login Required', $time, $time),
    (58, 'ru-RU', 'Требуется вход.', $time, $time),
    (58, 'uk-UA', 'Необхідно увійти', $time, $time),
    (59, 'en-US', 'The requested view "{name}" was not found.', $time, $time),
    (59, 'ru-RU', 'Запрашиваемый файл представления "{name}" не найден.', $time, $time),
    (59, 'uk-UA', 'Представлення "{name}" не знайдено.', $time, $time),
    (60, 'en-US', 'Invalid data received for parameter "{param}".', $time, $time),
    (60, 'ru-RU', 'Неправильное значение параметра "{param}".', $time, $time),
    (60, 'uk-UA', 'Отримано невірне значення для параметра "{param}".', $time, $time),
    (61, 'en-US', 'Missing required parameters: {params}', $time, $time),
    (61, 'ru-RU', 'Отсутствуют обязательные параметры: {params}', $time, $time),
    (61, 'uk-UA', 'Відсутні обовʼязкові параметри: {params}', $time, $time),
    (62, 'en-US', 'Unable to verify your data submission.', $time, $time),
    (62, 'ru-RU', 'Не удалось проверить переданные данные.', $time, $time),
    (62, 'uk-UA', 'Не вдалося перевірити передані дані.', $time, $time),
    (63, 'en-US', '{attribute} is invalid.', $time, $time),
    (63, 'ru-RU', 'Значение «{attribute}» неверно.', $time, $time),
    (63, 'uk-UA', 'Значення "{attribute}" не вірне.', $time, $time),
    (64, 'en-US', 'The combination {values} of {attributes} has already been taken.', $time, $time),
    (64, 'ru-RU', 'The combination {values} of {attributes} has already been taken.', $time, $time),
    (64, 'uk-UA', 'The combination {values} of {attributes} has already been taken.', $time, $time),
    (65, 'en-US', '{attribute} "{value}" has already been taken.', $time, $time),
    (65, 'ru-RU', 'Значение «{value}» для «{attribute}» уже занято.', $time, $time),
    (65, 'uk-UA', 'Значення «{value}» для «{attribute}» вже зайнято.', $time, $time),
    (66, 'en-US', 'File upload failed.', $time, $time),
    (66, 'ru-RU', 'Загрузка файла не удалась.', $time, $time),
    (66, 'uk-UA', 'Завантаження файлу не вдалося.', $time, $time),
    (67, 'en-US', 'Please upload a file.', $time, $time),
    (67, 'ru-RU', 'Загрузите файл.', $time, $time),
    (67, 'uk-UA', 'Будь ласка, завантажте файл.', $time, $time),
    (68, 'en-US', 'You can upload at most {limit, number} {limit, plural, one{file} other{files}}.', $time, $time),
    (68, 'ru-RU', 'Вы не можете загружать более {limit, number} {limit, plural, one{файла} few{файлов} many{файлов} other{файла}}.', $time, $time),
    (68, 'uk-UA', 'Ви не можете завантажувати більше {limit, number} {limit, plural, one{файла} few{файлів} many{файлів} other{файла}}.', $time, $time),
    (69, 'en-US', 'Only files with these extensions are allowed: {extensions}.', $time, $time),
    (69, 'ru-RU', 'Разрешена загрузка файлов только со следующими расширениями: {extensions}.', $time, $time),
    (69, 'uk-UA', 'Дозволені файли лише з наступними розширеннями: {extensions}.', $time, $time),
    (70, 'en-US', 'The file "{file}" is too big. Its size cannot exceed {formattedLimit}.', $time, $time),
    (70, 'ru-RU', 'Файл «{file}» слишком большой. Размер не должен превышать {formattedLimit}.', $time, $time),
    (70, 'uk-UA', 'Файл "{file}" занадто великий. Розмір не повинен перевищувати {formattedLimit}.', $time, $time),
    (71, 'en-US', 'The file "{file}" is too small. Its size cannot be smaller than {formattedLimit}.', $time, $time),
    (71, 'ru-RU', 'Файл «{file}» слишком маленький. Размер должен быть более {formattedLimit}.', $time, $time),
    (71, 'uk-UA', 'Файл "{file}" занадто малий. Розмір повинен бути більше, ніж {formattedLimit}.', $time, $time),
    (72, 'en-US', 'Only files with these MIME types are allowed: {mimeTypes}.', $time, $time),
    (72, 'ru-RU', 'Разрешена загрузка файлов только со следующими MIME-типами: {mimeTypes}.', $time, $time),
    (72, 'uk-UA', 'Дозволені файли лише з наступними MIME-типами: {mimeTypes}.', $time, $time),
    (73, 'en-US', 'The format of {attribute} is invalid.', $time, $time),
    (73, 'ru-RU', 'Неверный формат значения «{attribute}».', $time, $time),
    (73, 'uk-UA', 'Невірний формат значення "{attribute}".', $time, $time),
    (74, 'en-US', '{attribute} must be no less than {min}.', $time, $time),
    (74, 'ru-RU', 'Значение «{attribute}» должно быть не меньше {min}.', $time, $time),
    (74, 'uk-UA', 'Значення "{attribute}" має бути більшим {min}.', $time, $time),
    (75, 'en-US', '{attribute} must be no greater than {max}.', $time, $time),
    (75, 'ru-RU', 'Значение «{attribute}» не должно превышать {max}.', $time, $time),
    (75, 'uk-UA', 'Значення "{attribute}" не повинно перевищувати {max}.', $time, $time),
    (76, 'en-US', '{attribute} must be equal to "{compareValueOrAttribute}".', $time, $time),
    (76, 'ru-RU', 'Значение «{attribute}» должно быть равно «{compareValueOrAttribute}».', $time, $time),
    (76, 'uk-UA', 'Значення "{attribute}" повинно бути рівним "{compareValueOrAttribute}".', $time, $time),
    (77, 'en-US', '{attribute} must not be equal to "{compareValueOrAttribute}".', $time, $time),
    (77, 'ru-RU', 'Значение «{attribute}» не должно быть равно «{compareValueOrAttribute}».', $time, $time),
    (77, 'uk-UA', 'Значення "{attribute}" не повинно бути рівним "{compareValueOrAttribute}".', $time, $time),
    (78, 'en-US', '{attribute} must be greater than "{compareValueOrAttribute}".', $time, $time),
    (78, 'ru-RU', 'Значение «{attribute}» должно быть больше значения «{compareValueOrAttribute}».', $time, $time),
    (78, 'uk-UA', 'Значення "{attribute}" повинно бути більшим значення "{compareValueOrAttribute}".', $time, $time),
    (79, 'en-US', '{attribute} must be greater than or equal to "{compareValueOrAttribute}".', $time, $time),
    (79, 'ru-RU', 'Значение «{attribute}» должно быть больше или равно значения «{compareValueOrAttribute}».', $time, $time),
    (79, 'uk-UA', 'Значення "{attribute}" повинно бути більшим або дорівнювати значенню "{compareValueOrAttribute}".', $time, $time),
    (80, 'en-US', '{attribute} must be less than "{compareValueOrAttribute}".', $time, $time),
    (80, 'ru-RU', 'Значение «{attribute}» должно быть меньше значения «{compareValueOrAttribute}».', $time, $time),
    (80, 'uk-UA', 'Значення "{attribute}" повинно бути меншим значення "{compareValueOrAttribute}".', $time, $time),
    (81, 'en-US', '{attribute} must be less than or equal to "{compareValueOrAttribute}".', $time, $time),
    (81, 'ru-RU', 'Значение «{attribute}» должно быть меньше или равно значения «{compareValueOrAttribute}».', $time, $time),
    (81, 'uk-UA', 'Значення "{attribute}" повинно бути меншим або дорівнювати значенню "{compareValueOrAttribute}".', $time, $time),
    (82, 'en-US', 'the input value', $time, $time),
    (82, 'ru-RU', 'введённое значение', $time, $time),
    (82, 'uk-UA', 'введене значення', $time, $time),
    (83, 'en-US', '{attribute} must be a string.', $time, $time),
    (83, 'ru-RU', 'Значение «{attribute}» должно быть строкой.', $time, $time),
    (83, 'uk-UA', 'Значення "{attribute}" має бути текстовим рядком.', $time, $time),
    (84, 'en-US', '{attribute} should contain at least {min, number} {min, plural, one{character} other{characters}}.', $time, $time),
    (84, 'ru-RU', 'Значение «{attribute}» должно содержать минимум {min, number} {min, plural, one{символ} few{символа} many{символов} other{символа}}.', $time, $time),
    (84, 'uk-UA', 'Значення "{attribute}" повинно містити мінімум {min, number} {min, plural, one{символ} few{символа} many{символів} other{символа}}.', $time, $time),
    (85, 'en-US', '{attribute} should contain at most {max, number} {max, plural, one{character} other{characters}}.', $time, $time),
    (85, 'ru-RU', 'Значение «{attribute}» должно содержать максимум {max, number} {max, plural, one{символ} few{символа} many{символов} other{символа}}.', $time, $time),
    (85, 'uk-UA', 'Значення "{attribute}" повинно містити максимум {max, number} {max, plural, one{символ} few{символа} many{символів} other{символа}}.', $time, $time),
    (86, 'en-US', '{attribute} should contain {length, number} {length, plural, one{character} other{characters}}.', $time, $time),
    (86, 'ru-RU', 'Значение «{attribute}» должно содержать {length, number} {length, plural, one{символ} few{символа} many{символов} other{символа}}.', $time, $time),
    (86, 'uk-UA', 'Значення "{attribute}" повинно містити {length, number} {length, plural, one{символ} few{символа} many{символів} other{символа}}.', $time, $time),
    (87, 'en-US', '{attribute} must be an integer.', $time, $time),
    (87, 'ru-RU', 'Значение «{attribute}» должно быть целым числом.', $time, $time),
    (87, 'uk-UA', 'Значення "{attribute}" має бути цілим числом.', $time, $time),
    (88, 'en-US', '{attribute} must be a number.', $time, $time),
    (88, 'ru-RU', 'Значение «{attribute}» должно быть числом.', $time, $time),
    (88, 'uk-UA', 'Значення "{attribute}" має бути числом.', $time, $time),
    (89, 'en-US', '{attribute} must be either "{true}" or "{false}".', $time, $time),
    (89, 'ru-RU', 'Значение «{attribute}» должно быть равно «{true}» или «{false}».', $time, $time),
    (89, 'uk-UA', 'Значення "{attribute}" має дорівнювати "{true}" або "{false}".', $time, $time),
    (90, 'en-US', '{attribute} is not a valid email address.', $time, $time),
    (90, 'ru-RU', 'Значение «{attribute}» не является правильным email адресом.', $time, $time),
    (90, 'uk-UA', 'Значення "{attribute}" не є правильною email адресою.', $time, $time),
    (91, 'en-US', '{attribute} is not a valid URL.', $time, $time),
    (91, 'ru-RU', 'Значение «{attribute}» не является правильным URL.', $time, $time),
    (91, 'uk-UA', 'Значення "{attribute}" не є правильним URL.', $time, $time),
    (92, 'en-US', '{attribute} cannot be blank.', $time, $time),
    (92, 'ru-RU', 'Необходимо заполнить «{attribute}».', $time, $time),
    (92, 'uk-UA', 'Необхідно заповнити "{attribute}".', $time, $time),
    (93, 'en-US', '{attribute} must be "{requiredValue}".', $time, $time),
    (93, 'ru-RU', 'Значение «{attribute}» должно быть равно «{requiredValue}».', $time, $time),
    (93, 'uk-UA', 'Значення "{attribute}" має бути рівним "{requiredValue}".', $time, $time),
    (94, 'en-US', 'The file "{file}" is not an image.', $time, $time),
    (94, 'ru-RU', 'Файл «{file}» не является изображением.', $time, $time),
    (94, 'uk-UA', 'Файл "{file}" не є зображенням.', $time, $time),
    (95, 'en-US', 'The image "{file}" is too small. The width cannot be smaller than {limit, number} {limit, plural, one{pixel} other{pixels}}.', $time, $time),
    (95, 'ru-RU', 'Файл «{file}» слишком маленький. Ширина должна быть более {limit, number} {limit, plural, one{пиксель} few{пикселя} many{пикселей} other{пикселя}}.', $time, $time),
    (95, 'uk-UA', 'Зображення "{file}" занадто мале. Ширина повинна бути більше, ніж {limit, number} {limit, plural, one{піксель} few{пікселя} many{пікселів} other{пікселя}}.', $time, $time),
    (96, 'en-US', 'The image "{file}" is too small. The height cannot be smaller than {limit, number} {limit, plural, one{pixel} other{pixels}}.', $time, $time),
    (96, 'ru-RU', 'Файл «{file}» слишком маленький. Высота должна быть более {limit, number} {limit, plural, one{пиксель} few{пикселя} many{пикселей} other{пикселя}}.', $time, $time),
    (96, 'uk-UA', 'Зображення "{file}" занадто мале. Висота повинна бути більше, ніж {limit, number} {limit, plural, one{піксель} few{пікселя} many{пікселів} other{пікселя}}.', $time, $time),
    (97, 'en-US', 'The image "{file}" is too large. The width cannot be larger than {limit, number} {limit, plural, one{pixel} other{pixels}}.', $time, $time),
    (97, 'ru-RU', 'Файл «{file}» слишком большой. Ширина не должна превышать {limit, number} {limit, plural, one{пиксель} few{пикселя} many{пикселей} other{пикселя}}.', $time, $time),
    (97, 'uk-UA', 'Зображення "{file}" занадто велике. Ширина не повинна перевищувати {limit, number} {limit, plural, one{піксель} few{пікселя} many{пікселів} other{пікселя}}.', $time, $time),
    (98, 'en-US', 'The image "{file}" is too large. The height cannot be larger than {limit, number} {limit, plural, one{pixel} other{pixels}}.', $time, $time),
    (98, 'ru-RU', 'Файл «{file}» слишком большой. Высота не должна превышать {limit, number} {limit, plural, one{пиксель} few{пикселя} many{пикселей} other{пикселя}}.', $time, $time),
    (98, 'uk-UA', 'Зображення "{file}" занадто велике. Висота не повинна перевищувати {limit, number} {limit, plural, one{піксель} few{пікселя} many{пікселів} other{пікселя}}.', $time, $time),
    (99, 'en-US', '{attribute} must be a valid IP address.', $time, $time),
    (99, 'ru-RU', 'Значение «{attribute}» должно быть правильным IP адресом.', $time, $time),
    (99, 'uk-UA', 'Значення «{attribute}» повинно бути правильною IP адресою.', $time, $time),
    (100, 'en-US', '{attribute} must not be an IPv6 address.', $time, $time),
    (100, 'ru-RU', 'Значение «{attribute}» не должно быть IPv6 адресом.', $time, $time),
    (100, 'uk-UA', 'Значення «{attribute}» не повинно бути IPv6 адресою.', $time, $time),
    (101, 'en-US', '{attribute} must not be an IPv4 address.', $time, $time),
    (101, 'ru-RU', 'Значение «{attribute}» не должно быть IPv4 адресом.', $time, $time),
    (101, 'uk-UA', 'Значення «{attribute}» не повинно бути IPv4 адресою.', $time, $time),
    (102, 'en-US', '{attribute} contains wrong subnet mask.', $time, $time),
    (102, 'ru-RU', 'Значение «{attribute}» содержит неверную маску подсети.', $time, $time),
    (102, 'uk-UA', 'Значення «{attribute}» містить неправильну маску підмережі.', $time, $time),
    (103, 'en-US', '{attribute} must be an IP address with specified subnet.', $time, $time),
    (103, 'ru-RU', 'Значение «{attribute}» должно быть IP адресом с подсетью.', $time, $time),
    (103, 'uk-UA', 'Значення «{attribute}» повинно бути IP адресою з підмережею.', $time, $time),
    (104, 'en-US', '{attribute} must not be a subnet.', $time, $time),
    (104, 'ru-RU', 'Значение «{attribute}» не должно быть подсетью.', $time, $time),
    (104, 'uk-UA', 'Значення «{attribute}» не повинно бути підмережею.', $time, $time),
    (105, 'en-US', '{attribute} is not in the allowed range.', $time, $time),
    (105, 'ru-RU', 'Значение «{attribute}» не входит в список разрешенных диапазонов адресов.', $time, $time),
    (105, 'uk-UA', 'Значення «{attribute}» не входить в список дозволених діапазонів адрес.', $time, $time),
    (106, 'en-US', 'The verification code is incorrect.', $time, $time),
    (106, 'ru-RU', 'Неправильный проверочный код.', $time, $time),
    (106, 'uk-UA', 'Невірний код перевірки.', $time, $time),
    (107, 'en-US', 'View', $time, $time),
    (107, 'ru-RU', 'Просмотр', $time, $time),
    (107, 'uk-UA', 'Переглянути', $time, $time),
    (108, 'en-US', 'Update', $time, $time),
    (108, 'ru-RU', 'Редактировать', $time, $time),
    (108, 'uk-UA', 'Оновити', $time, $time),
    (109, 'en-US', 'Delete', $time, $time),
    (109, 'ru-RU', 'Удалить', $time, $time),
    (109, 'uk-UA', 'Видалити', $time, $time),
    (110, 'en-US', 'Are you sure you want to delete this item?', $time, $time),
    (110, 'ru-RU', 'Вы уверены, что хотите удалить этот элемент?', $time, $time),
    (110, 'uk-UA', 'Ви впевнені, що хочете видалити цей елемент?', $time, $time),
    (111, 'en-US', 'Please fix the following errors:', $time, $time),
    (111, 'ru-RU', 'Исправьте следующие ошибки:', $time, $time),
    (111, 'uk-UA', 'Будь ласка, виправте наступні помилки:', $time, $time),
    (112, 'en-US', '{percent}% Complete', $time, $time),
    (112, 'ru-RU', '{percent}% Выполнено', $time, $time),
    (112, 'uk-UA', '{percent}% Виконано', $time, $time),
    (113, 'en-US', 'Update translation', $time, $time),
    (113, 'ru-RU', 'Изменить перевод', $time, $time),
    (113, 'uk-UA', 'Змінити перевод', $time, $time),
    (114, 'en-US', 'Interface translations', $time, $time),
    (114, 'ru-RU', 'Переводы интерфейса', $time, $time),
    (114, 'uk-UA', 'Переклади інтерфейса', $time, $time),
    (115, 'en-US', 'Create', $time, $time),
    (115, 'ru-RU', 'Создать', $time, $time),
    (115, 'uk-UA', 'Створити', $time, $time),
    (116, 'en-US', 'Update', $time, $time),
    (116, 'ru-RU', 'Обновить', $time, $time),
    (116, 'uk-UA', 'Оновити', $time, $time),
    (117, 'en-US', 'Translation ({language})', $time, $time),
    (117, 'ru-RU', 'Перевод ({language})', $time, $time),
    (117, 'uk-UA', 'Переклад ({language})', $time, $time),
    (118, 'en-US', 'Add language', $time, $time),
    (118, 'ru-RU', 'Добавить язык', $time, $time),
    (118, 'uk-UA', 'Додати мову', $time, $time),
    (119, 'en-US', 'Languages', $time, $time),
    (119, 'ru-RU', 'Языки', $time, $time),
    (119, 'uk-UA', 'Мови', $time, $time),
    (120, 'en-US', 'Update language:', $time, $time),
    (120, 'ru-RU', 'Изменение языка:', $time, $time),
    (120, 'uk-UA', 'Зміна мови:', $time, $time),
    (121, 'en-US', 'If you select this option here, it will be reset everywhere', $time, $time),
    (121, 'ru-RU', 'Если Вы выберете данную опцию здесь, она будет сброшена везде', $time, $time),
    (121, 'uk-UA', 'Якщо Ви виберете цю опцію тут, вона буде скинута всюди', $time, $time),
    (122, 'en-US', 'Update language', $time, $time),
    (122, 'ru-RU', 'Изменение языка', $time, $time),
    (122, 'uk-UA', 'Оновлення мови', $time, $time),
    (123, 'en-US', 'The combination of ID and Language has already been taken.', $time, $time),
    (123, 'ru-RU', 'Данное сочетание ID и языка уже существует', $time, $time),
    (123, 'uk-UA', 'Дане поєднання ID і мови вже існує', $time, $time),
    (124, 'en-US', 'ID', $time, $time),
    (124, 'ru-RU', 'ID', $time, $time),
    (124, 'uk-UA', 'ID', $time, $time),
    (125, 'en-US', 'Language', $time, $time),
    (125, 'ru-RU', 'Язык', $time, $time),
    (125, 'uk-UA', 'Мова', $time, $time),
    (126, 'en-US', 'Translation', $time, $time),
    (126, 'ru-RU', 'Перевод', $time, $time),
    (126, 'uk-UA', 'Переклад', $time, $time),
    (127, 'en-US', 'You can only override the default language', $time, $time),
    (127, 'ru-RU', 'Вы можете только изменить язык установленный по умолчанию', $time, $time),
    (127, 'uk-UA', 'Ви можете тільки змінити мову встановлену за замовчуванням', $time, $time),
    (128, 'en-US', 'Url (ISO 639-1)', $time, $time),
    (128, 'ru-RU', 'Url (ISO 639-1)', $time, $time),
    (128, 'uk-UA', 'Url (ISO 639-1)', $time, $time),
    (129, 'en-US', 'Locale', $time, $time),
    (129, 'ru-RU', 'Локаль', $time, $time),
    (129, 'uk-UA', 'Локаль', $time, $time),
    (130, 'en-US', 'Name', $time, $time),
    (130, 'ru-RU', 'Название', $time, $time),
    (130, 'uk-UA', 'Назва', $time, $time),
    (131, 'en-US', 'Is Default', $time, $time),
    (131, 'ru-RU', 'По умолчанию', $time, $time),
    (131, 'uk-UA', 'За замовчуванням', $time, $time),
    (132, 'en-US', 'Created At', $time, $time),
    (132, 'ru-RU', 'Создано', $time, $time),
    (132, 'uk-UA', 'Створено', $time, $time),
    (133, 'en-US', 'Updated At', $time, $time),
    (133, 'ru-RU', 'Обновлено', $time, $time),
    (133, 'uk-UA', 'Оновлено', $time, $time),
    (134, 'en-US', 'Message category', $time, $time),
    (134, 'ru-RU', 'Категория перевода', $time, $time),
    (134, 'uk-UA', 'Категорія перекладу', $time, $time),
    (135, 'en-US', 'Message key', $time, $time),
    (135, 'ru-RU', 'Ключ перевода', $time, $time),
    (135, 'uk-UA', 'Ключ перекладу', $time, $time),
    (136, 'en-US', 'The requested translation does not exist', $time, $time),
    (136, 'ru-RU', 'Запрашиваемый перевод не существует', $time, $time),
    (136, 'uk-UA', 'Запитуваний переклад не існує', $time, $time),
    (137, 'en-US', 'Translation updated successfully!', $time, $time),
    (137, 'ru-RU', 'Перевод успешно изменен!', $time, $time),
    (137, 'uk-UA', 'Переклад змінено успішно!', $time, $time),
    (138, 'en-US', 'The requested language does not exist', $time, $time),
    (138, 'ru-RU', 'Запрашиваемый язык не существует', $time, $time),
    (138, 'uk-UA', 'Запитувана мова не існує', $time, $time),
    (139, 'en-US', 'You can''t delete default language!', $time, $time),
    (139, 'ru-RU', 'Вы не можете удалить язык по умолчанию!', $time, $time),
    (139, 'uk-UA', 'Ви не можете видалити мову за замовчуванням!', $time, $time),
    (140, 'en-US', 'Language deleted successfully!', $time, $time),
    (140, 'ru-RU', 'Язык удален успешно!', $time, $time),
    (140, 'uk-UA', 'Мову видалено успішно!', $time, $time),
    (141, 'en-US', 'Language updated successfully!', $time, $time),
    (141, 'ru-RU', 'Язык изменен успешно!', $time, $time),
    (141, 'uk-UA', 'Мова змінена успішно!', $time, $time),
    (142, 'en-US', 'Language created successfully!', $time, $time),
    (142, 'ru-RU', 'Язык создан успешно!', $time, $time),
    (142, 'uk-UA', 'Мова створена успішно!', $time, $time),
    (143, 'en-US', 'Русский', $time, $time),
    (143, 'ru-RU', 'Русский', $time, $time),
    (143, 'uk-UA', 'Русский', $time, $time),
    (144, 'en-US', 'Українська', $time, $time),
    (144, 'ru-RU', 'Українська', $time, $time),
    (144, 'uk-UA', 'Українська', $time, $time),
    (145, 'en-US', 'English', $time, $time),
    (145, 'ru-RU', 'English', $time, $time),
    (145, 'uk-UA', 'English', $time, $time),
    (146, 'en-US', 'Enter a url...', $time, $time),
    (146, 'ru-RU', 'Введите url...', $time, $time),
    (146, 'uk-UA', 'Введіть url...', $time, $time),
    (147, 'en-US', 'Enter a locale...', $time, $time),
    (147, 'ru-RU', 'Введите локаль...', $time, $time),
    (147, 'uk-UA', 'Введіть локаль...', $time, $time),
    (148, 'en-US', 'Enter a name...', $time, $time),
    (148, 'ru-RU', 'Введите имя...', $time, $time),
    (148, 'uk-UA', 'Введіть ім’я...', $time, $time),
    (149, 'en-US', 'Enter a translate...', $time, $time),
    (149, 'ru-RU', 'Введите перевод...', $time, $time),
    (149, 'uk-UA', 'Введіть переклад...', $time, $time);
SQL
        );
    }

}
