<?php
use xz1mefx\multilang\models\Language;
use xz1mefx\multilang\models\Message;
use xz1mefx\multilang\models\SourceMessage;
use yii\db\Migration;

class m161210_131014_multilang_init extends Migration
{
    public function up()
    {
        $this->down();

        $tableOptions = NULL;
        if ($this->db->driverName === 'mysql') {
            // http://stackoverflow.com/questions/766809/whats-the-difference-between-utf8-general-ci-and-utf8-unicode-ci
            $tableOptions = 'CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE=InnoDB';
        }


        // -------------------------------------------
        // Create langs tables
        // -------------------------------------------

        // Language table
        $this->createTable(Language::TABLE_NAME, [
            'id' => $this->primaryKey()->unsigned(),
            'url' => $this->string(2)->notNull()->unique(),
            'locale' => $this->string(16)->notNull()->unique(),
            'name' => $this->string()->notNull(),
            'default' => $this->smallInteger(1)->notNull()->defaultValue(0),

            'created_at' => $this->integer()->notNull(),
            'updated_at' => $this->integer()->notNull(),
        ], $tableOptions);

        // Add default languages
        $this->insert(Language::TABLE_NAME, [
            'url' => 'ru',
            'locale' => 'ru-RU',
            'name' => 'Русский',
            'created_at' => time(),
            'updated_at' => time(),
        ]);
        $this->insert(Language::TABLE_NAME, [
            'url' => 'uk',
            'locale' => 'uk-UA',
            'name' => 'Українська',
            'created_at' => time(),
            'updated_at' => time(),
        ]);
        $this->insert(Language::TABLE_NAME, [
            'url' => 'en',
            'locale' => 'en-US',
            'name' => 'English',
            'default' => 1,
            'created_at' => time(),
            'updated_at' => time(),
        ]);

        // Add translate tables
        $this->createTable(SourceMessage::TABLE_NAME, [
            'id' => $this->primaryKey()->unsigned(),
            'category' => $this->string(32),
            'message' => $this->text()->notNull(),

            'created_at' => $this->integer()->notNull(),
            'updated_at' => $this->integer()->notNull(),
        ], $tableOptions);
        $this->createTable(Message::TABLE_NAME, [
            'id' => $this->integer()->unsigned(),
            'language' => $this->string(16),
            'translation' => $this->text(),

            'created_at' => $this->integer()->notNull(),
            'updated_at' => $this->integer()->notNull(),
        ], $tableOptions);

        $this->createIndex('message_id_language', Message::TABLE_NAME, ['id', 'language'], TRUE);
        $this->addForeignKey('fk_message_source_message', Message::TABLE_NAME, 'id', SourceMessage::TABLE_NAME, 'id', 'CASCADE', 'CASCADE');


        // -------------------------------------------
        // Insert default source messages
        // -------------------------------------------

        $sourceMessageTable = SourceMessage::TABLE_NAME;

        $this->execute(<<<SQL
INSERT INTO {$sourceMessageTable} (`id`, `category`, `message`, `created_at`, `updated_at`) VALUES
    (1, 'yii', 'Home', 0, 0),
    (2, 'yii', 'No results found.', 0, 0),
    (3, 'yii', 'Showing <b>{begin, number}-{end, number}</b> of <b>{totalCount, number}</b> {totalCount, plural, one{item} other{items}}.', 0, 0),
    (4, 'yii', 'Total <b>{count, number}</b> {count, plural, one{item} other{items}}.', 0, 0),
    (5, 'yii', 'Unknown alias: -{name}', 0, 0),
    (6, 'yii', 'Unknown option: --{name}', 0, 0),
    (7, 'yii', 'Missing required arguments: {params}', 0, 0),
    (8, 'yii', 'No', 0, 0),
    (9, 'yii', 'Yes', 0, 0),
    (10, 'yii', '(not set)', 0, 0),
    (11, 'yii', 'in {delta, plural, =1{a year} other{# years}}', 0, 0),
    (12, 'yii', 'in {delta, plural, =1{a month} other{# months}}', 0, 0),
    (13, 'yii', 'in {delta, plural, =1{a day} other{# days}}', 0, 0),
    (14, 'yii', 'in {delta, plural, =1{an hour} other{# hours}}', 0, 0),
    (15, 'yii', 'in {delta, plural, =1{a minute} other{# minutes}}', 0, 0),
    (16, 'yii', 'just now', 0, 0),
    (17, 'yii', 'in {delta, plural, =1{a second} other{# seconds}}', 0, 0),
    (18, 'yii', '{delta, plural, =1{a year} other{# years}} ago', 0, 0),
    (19, 'yii', '{delta, plural, =1{a month} other{# months}} ago', 0, 0),
    (20, 'yii', '{delta, plural, =1{a day} other{# days}} ago', 0, 0),
    (21, 'yii', '{delta, plural, =1{an hour} other{# hours}} ago', 0, 0),
    (22, 'yii', '{delta, plural, =1{a minute} other{# minutes}} ago', 0, 0),
    (23, 'yii', '{delta, plural, =1{a second} other{# seconds}} ago', 0, 0),
    (24, 'yii', '{delta, plural, =1{1 year} other{# years}}', 0, 0),
    (25, 'yii', '{delta, plural, =1{1 month} other{# months}}', 0, 0),
    (26, 'yii', '{delta, plural, =1{1 day} other{# days}}', 0, 0),
    (27, 'yii', '{delta, plural, =1{1 hour} other{# hours}}', 0, 0),
    (28, 'yii', '{delta, plural, =1{1 minute} other{# minutes}}', 0, 0),
    (29, 'yii', '{delta, plural, =1{1 second} other{# seconds}}', 0, 0),
    (30, 'yii', '{nFormatted} B', 0, 0),
    (31, 'yii', '{nFormatted} KiB', 0, 0),
    (32, 'yii', '{nFormatted} MiB', 0, 0),
    (33, 'yii', '{nFormatted} GiB', 0, 0),
    (34, 'yii', '{nFormatted} TiB', 0, 0),
    (35, 'yii', '{nFormatted} PiB', 0, 0),
    (36, 'yii', '{nFormatted} KB', 0, 0),
    (37, 'yii', '{nFormatted} MB', 0, 0),
    (38, 'yii', '{nFormatted} GB', 0, 0),
    (39, 'yii', '{nFormatted} TB', 0, 0),
    (40, 'yii', '{nFormatted} PB', 0, 0),
    (41, 'yii', '{nFormatted} {n, plural, =1{byte} other{bytes}}', 0, 0),
    (42, 'yii', '{nFormatted} {n, plural, =1{kibibyte} other{kibibytes}}', 0, 0),
    (43, 'yii', '{nFormatted} {n, plural, =1{mebibyte} other{mebibytes}}', 0, 0),
    (44, 'yii', '{nFormatted} {n, plural, =1{gibibyte} other{gibibytes}}', 0, 0),
    (45, 'yii', '{nFormatted} {n, plural, =1{tebibyte} other{tebibytes}}', 0, 0),
    (46, 'yii', '{nFormatted} {n, plural, =1{pebibyte} other{pebibytes}}', 0, 0),
    (47, 'yii', '{nFormatted} {n, plural, =1{kilobyte} other{kilobytes}}', 0, 0),
    (48, 'yii', '{nFormatted} {n, plural, =1{megabyte} other{megabytes}}', 0, 0),
    (49, 'yii', '{nFormatted} {n, plural, =1{gigabyte} other{gigabytes}}', 0, 0),
    (50, 'yii', '{nFormatted} {n, plural, =1{terabyte} other{terabytes}}', 0, 0),
    (51, 'yii', '{nFormatted} {n, plural, =1{petabyte} other{petabytes}}', 0, 0),
    (52, 'yii', 'You are not allowed to perform this action.', 0, 0),
    (53, 'yii', 'Powered by {yii}', 0, 0),
    (54, 'yii', 'Yii Framework', 0, 0),
    (55, 'yii', 'Page not found.', 0, 0),
    (56, 'yii', 'Error', 0, 0),
    (57, 'yii', 'An internal server error occurred.', 0, 0),
    (58, 'yii', 'Login Required', 0, 0),
    (59, 'yii', 'The requested view "{name}" was not found.', 0, 0),
    (60, 'yii', 'Invalid data received for parameter "{param}".', 0, 0),
    (61, 'yii', 'Missing required parameters: {params}', 0, 0),
    (62, 'yii', 'Unable to verify your data submission.', 0, 0),
    (63, 'yii', '{attribute} is invalid.', 0, 0),
    (64, 'yii', 'The combination {values} of {attributes} has already been taken.', 0, 0),
    (65, 'yii', '{attribute} "{value}" has already been taken.', 0, 0),
    (66, 'yii', 'File upload failed.', 0, 0),
    (67, 'yii', 'Please upload a file.', 0, 0),
    (68, 'yii', 'You can upload at most {limit, number} {limit, plural, one{file} other{files}}.', 0, 0),
    (69, 'yii', 'Only files with these extensions are allowed: {extensions}.', 0, 0),
    (70, 'yii', 'The file "{file}" is too big. Its size cannot exceed {formattedLimit}.', 0, 0),
    (71, 'yii', 'The file "{file}" is too small. Its size cannot be smaller than {formattedLimit}.', 0, 0),
    (72, 'yii', 'Only files with these MIME types are allowed: {mimeTypes}.', 0, 0),
    (73, 'yii', 'The format of {attribute} is invalid.', 0, 0),
    (74, 'yii', '{attribute} must be no less than {min}.', 0, 0),
    (75, 'yii', '{attribute} must be no greater than {max}.', 0, 0),
    (76, 'yii', '{attribute} must be equal to "{compareValueOrAttribute}".', 0, 0),
    (77, 'yii', '{attribute} must not be equal to "{compareValueOrAttribute}".', 0, 0),
    (78, 'yii', '{attribute} must be greater than "{compareValueOrAttribute}".', 0, 0),
    (79, 'yii', '{attribute} must be greater than or equal to "{compareValueOrAttribute}".', 0, 0),
    (80, 'yii', '{attribute} must be less than "{compareValueOrAttribute}".', 0, 0),
    (81, 'yii', '{attribute} must be less than or equal to "{compareValueOrAttribute}".', 0, 0),
    (82, 'yii', 'the input value', 0, 0),
    (83, 'yii', '{attribute} must be a string.', 0, 0),
    (84, 'yii', '{attribute} should contain at least {min, number} {min, plural, one{character} other{characters}}.', 0, 0),
    (85, 'yii', '{attribute} should contain at most {max, number} {max, plural, one{character} other{characters}}.', 0, 0),
    (86, 'yii', '{attribute} should contain {length, number} {length, plural, one{character} other{characters}}.', 0, 0),
    (87, 'yii', '{attribute} must be an integer.', 0, 0),
    (88, 'yii', '{attribute} must be a number.', 0, 0),
    (89, 'yii', '{attribute} must be either "{true}" or "{false}".', 0, 0),
    (90, 'yii', '{attribute} is not a valid email address.', 0, 0),
    (91, 'yii', '{attribute} is not a valid URL.', 0, 0),
    (92, 'yii', '{attribute} cannot be blank.', 0, 0),
    (93, 'yii', '{attribute} must be "{requiredValue}".', 0, 0),
    (94, 'yii', 'The file "{file}" is not an image.', 0, 0),
    (95, 'yii', 'The image "{file}" is too small. The width cannot be smaller than {limit, number} {limit, plural, one{pixel} other{pixels}}.', 0, 0),
    (96, 'yii', 'The image "{file}" is too small. The height cannot be smaller than {limit, number} {limit, plural, one{pixel} other{pixels}}.', 0, 0),
    (97, 'yii', 'The image "{file}" is too large. The width cannot be larger than {limit, number} {limit, plural, one{pixel} other{pixels}}.', 0, 0),
    (98, 'yii', 'The image "{file}" is too large. The height cannot be larger than {limit, number} {limit, plural, one{pixel} other{pixels}}.', 0, 0),
    (99, 'yii', '{attribute} must be a valid IP address.', 0, 0),
    (100, 'yii', '{attribute} must not be an IPv6 address.', 0, 0),
    (101, 'yii', '{attribute} must not be an IPv4 address.', 0, 0),
    (102, 'yii', '{attribute} contains wrong subnet mask.', 0, 0),
    (103, 'yii', '{attribute} must be an IP address with specified subnet.', 0, 0),
    (104, 'yii', '{attribute} must not be a subnet.', 0, 0),
    (105, 'yii', '{attribute} is not in the allowed range.', 0, 0),
    (106, 'yii', 'The verification code is incorrect.', 0, 0),
    (107, 'yii', 'View', 0, 0),
    (108, 'yii', 'Update', 0, 0),
    (109, 'yii', 'Delete', 0, 0),
    (110, 'yii', 'Are you sure you want to delete this item?', 0, 0),
    (111, 'yii', 'Please fix the following errors:', 0, 0),
    (112, 'yii', '{percent}% Complete', 0, 0),
    (113, 'multilang-tools', 'Update translation', 0, 0),
    (114, 'multilang-tools', 'Interface translations', 0, 0),
    (115, 'multilang-tools', 'Create', 0, 0),
    (116, 'multilang-tools', 'Update', 0, 0),
    (117, 'multilang-tools', 'Translation ({language})', 0, 0),
    (118, 'multilang-tools', 'Add language', 0, 0),
    (119, 'multilang-tools', 'Languages', 0, 0),
    (120, 'multilang-tools', 'Update language:', 0, 0),
    (121, 'multilang-tools', 'If you select this option here, it will be reset everywhere', 0, 0),
    (122, 'multilang-tools', 'Update language', 0, 0),
    (123, 'multilang-tools', 'The combination of ID and Language has already been taken.', 0, 0),
    (124, 'multilang-tools', 'ID', 0, 0),
    (125, 'multilang-tools', 'Language', 0, 0),
    (126, 'multilang-tools', 'Translation', 0, 0),
    (127, 'multilang-tools', 'You can only override the default language', 0, 0),
    (128, 'multilang-tools', 'Url (ISO 639-1)', 0, 0),
    (129, 'multilang-tools', 'Locale', 0, 0),
    (130, 'multilang-tools', 'Name', 0, 0),
    (131, 'multilang-tools', 'Is Default', 0, 0),
    (132, 'multilang-tools', 'Created At', 0, 0),
    (133, 'multilang-tools', 'Updated At', 0, 0),
    (134, 'multilang-tools', 'Message category', 0, 0),
    (135, 'multilang-tools', 'Message key', 0, 0),
    (136, 'multilang-tools', 'The requested translation does not exist', 0, 0),
    (137, 'multilang-tools', 'Translation updated successfully!', 0, 0),
    (138, 'multilang-tools', 'The requested language does not exist', 0, 0),
    (139, 'multilang-tools', 'You can''t delete default language!', 0, 0),
    (140, 'multilang-tools', 'Language deleted successfully!', 0, 0),
    (141, 'multilang-tools', 'Language updated successfully!', 0, 0),
    (142, 'multilang-tools', 'Language created successfully!', 0, 0),
    (143, 'multilang-tools', 'Русский', 0, 0),
    (144, 'multilang-tools', 'Українська', 0, 0),
    (145, 'multilang-tools', 'English', 0, 0);
SQL
        );


        // -------------------------------------------
        // Insert default messages
        // -------------------------------------------

        $messageTable = Message::TABLE_NAME;

        $this->execute(<<<SQL
INSERT INTO {$messageTable} (`id`, `language`, `translation`, `created_at`, `updated_at`) VALUES
    (1, 'en-US', 'Home', 0, 0),
    (1, 'ru-RU', 'Главная', 0, 0),
    (1, 'uk-UA', 'Головна', 0, 0),
    (2, 'en-US', 'No results found.', 0, 0),
    (2, 'ru-RU', 'Ничего не найдено.', 0, 0),
    (2, 'uk-UA', 'Нічого не знайдено.', 0, 0),
    (3, 'en-US', 'Showing <b>{begin, number}-{end, number}</b> of <b>{totalCount, number}</b> {totalCount, plural, one{item} other{items}}.', 0, 0),
    (3, 'ru-RU', 'Показаны записи <b>{begin, number}-{end, number}</b> из <b>{totalCount, number}</b>.', 0, 0),
    (3, 'uk-UA', 'Показані <b>{begin, number}-{end, number}</b> із <b>{totalCount, number}</b> {totalCount, plural, one{запису} other{записів}}.', 0, 0),
    (4, 'en-US', 'Total <b>{count, number}</b> {count, plural, one{item} other{items}}.', 0, 0),
    (4, 'ru-RU', 'Всего <b>{count, number}</b> {count, plural, one{запись} few{записи} many{записей} other{записи}}.', 0, 0),
    (4, 'uk-UA', 'Всього <b>{count, number}</b> {count, plural, one{запис} few{записи} many{записів} other{записи}}.', 0, 0),
    (5, 'en-US', 'Unknown alias: -{name}', 0, 1481716923),
    (5, 'ru-RU', 'Unknown alias: -{name}', 0, 1481716923),
    (5, 'uk-UA', 'Unknown alias: -{name}', 0, 1481716923),
    (6, 'en-US', 'Unknown option: --{name}', 0, 0),
    (6, 'ru-RU', 'Неизвестная опция: --{name}', 0, 0),
    (6, 'uk-UA', 'Невідома опція : --{name}', 0, 0),
    (7, 'en-US', 'Missing required arguments: {params}', 0, 0),
    (7, 'ru-RU', 'Отсутствуют обязательные аргументы: {params}', 0, 0),
    (7, 'uk-UA', 'Відсутні обовʼязкові аргументи: {params}', 0, 0),
    (8, 'en-US', 'No', 0, 0),
    (8, 'ru-RU', 'Нет', 0, 0),
    (8, 'uk-UA', 'Ні', 0, 0),
    (9, 'en-US', 'Yes', 0, 0),
    (9, 'ru-RU', 'Да', 0, 0),
    (9, 'uk-UA', 'Так', 0, 0),
    (10, 'en-US', '(not set)', 0, 0),
    (10, 'ru-RU', '(не задано)', 0, 0),
    (10, 'uk-UA', '(не задано)', 0, 0),
    (11, 'en-US', 'in {delta, plural, =1{a year} other{# years}}', 0, 0),
    (11, 'ru-RU', 'через {delta, plural, =1{год} one{# год} few{# года} many{# лет} other{# года}}', 0, 0),
    (11, 'uk-UA', 'через {delta, plural, =1{рік} one{# рік} few{# роки} many{# років} other{# роки}}', 0, 0),
    (12, 'en-US', 'in {delta, plural, =1{a month} other{# months}}', 0, 0),
    (12, 'ru-RU', 'через {delta, plural, =1{месяц} one{# месяц} few{# месяца} many{# месяцев} other{# месяца}}', 0, 0),
    (12, 'uk-UA', 'через {delta, plural, =1{місяць} one{# місяць} few{# місяці} many{# місяців} other{# місяці}}', 0, 0),
    (13, 'en-US', 'in {delta, plural, =1{a day} other{# days}}', 0, 0),
    (13, 'ru-RU', 'через {delta, plural, =1{день} one{# день} few{# дня} many{# дней} other{# дня}}', 0, 0),
    (13, 'uk-UA', 'через {delta, plural, =1{день} one{# день} few{# дні} many{# днів} other{# дні}}', 0, 0),
    (14, 'en-US', 'in {delta, plural, =1{an hour} other{# hours}}', 0, 0),
    (14, 'ru-RU', 'через {delta, plural, =1{час} one{# час} few{# часа} many{# часов} other{# часа}}', 0, 0),
    (14, 'uk-UA', 'через {delta, plural, =1{годину} one{# годину} few{# години} many{# годин} other{# години}}', 0, 0),
    (15, 'en-US', 'in {delta, plural, =1{a minute} other{# minutes}}', 0, 0),
    (15, 'ru-RU', 'через {delta, plural, =1{минуту} one{# минуту} few{# минуты} many{# минут} other{# минуты}}', 0, 0),
    (15, 'uk-UA', 'через {delta, plural, =1{хвилину} one{# хвилину} few{# хвилини} many{# хвилин} other{# хвилини}}', 0, 0),
    (16, 'en-US', 'just now', 0, 0),
    (16, 'ru-RU', 'прямо сейчас', 0, 0),
    (16, 'uk-UA', 'саме зараз', 0, 0),
    (17, 'en-US', 'in {delta, plural, =1{a second} other{# seconds}}', 0, 0),
    (17, 'ru-RU', 'через {delta, plural, =1{секунду} one{# секунду} few{# секунды} many{# секунд} other{# секунды}}', 0, 0),
    (17, 'uk-UA', 'через {delta, plural, =1{секунду} one{# секунду} few{# секунди} many{# секунд} other{# секунди}}', 0, 0),
    (18, 'en-US', '{delta, plural, =1{a year} other{# years}} ago', 0, 0),
    (18, 'ru-RU', '{delta, plural, =1{год} one{# год} few{# года} many{# лет} other{# года}} назад', 0, 0),
    (18, 'uk-UA', '{delta, plural, =1{рік} one{# рік} few{# роки} many{# років} other{# роки}} тому', 0, 0),
    (19, 'en-US', '{delta, plural, =1{a month} other{# months}} ago', 0, 0),
    (19, 'ru-RU', '{delta, plural, =1{месяц} one{# месяц} few{# месяца} many{# месяцев} other{# месяца}} назад', 0, 0),
    (19, 'uk-UA', '{delta, plural, =1{місяць} one{# місяць} few{# місяці} many{# місяців} other{# місяці}} тому', 0, 0),
    (20, 'en-US', '{delta, plural, =1{a day} other{# days}} ago', 0, 0),
    (20, 'ru-RU', '{delta, plural, =1{день} one{# день} few{# дня} many{# дней} other{# дня}} назад', 0, 0),
    (20, 'uk-UA', '{delta, plural, =1{день} one{# день} few{# дні} many{# днів} other{# дні}} тому', 0, 0),
    (21, 'en-US', '{delta, plural, =1{an hour} other{# hours}} ago', 0, 0),
    (21, 'ru-RU', '{delta, plural, =1{час} one{# час} few{# часа} many{# часов} other{# часа}} назад', 0, 0),
    (21, 'uk-UA', '{delta, plural, =1{година} one{# година} few{# години} many{# годин} other{# години}} тому', 0, 0),
    (22, 'en-US', '{delta, plural, =1{a minute} other{# minutes}} ago', 0, 0),
    (22, 'ru-RU', '{delta, plural, =1{минуту} one{# минуту} few{# минуты} many{# минут} other{# минуты}} назад', 0, 0),
    (22, 'uk-UA', '{delta, plural, =1{хвилину} one{# хвилину} few{# хвилини} many{# хвилин} other{# хвилини}} тому', 0, 0),
    (23, 'en-US', '{delta, plural, =1{a second} other{# seconds}} ago', 0, 0),
    (23, 'ru-RU', '{delta, plural, =1{секунду} one{# секунду} few{# секунды} many{# секунд} other{# секунды}} назад', 0, 0),
    (23, 'uk-UA', '{delta, plural, =1{секунду} one{# секунду} few{# секунди} many{# секунд} other{# секунди}} тому', 0, 0),
    (24, 'en-US', '{delta, plural, =1{1 year} other{# years}}', 0, 0),
    (24, 'ru-RU', '{delta, plural, one{# год} few{# года} many{# лет} other{# лет}}', 0, 0),
    (24, 'uk-UA', '{delta, plural, one{# рік} few{# роки} many{# років} other{# років}}', 0, 0),
    (25, 'en-US', '{delta, plural, =1{1 month} other{# months}}', 0, 0),
    (25, 'ru-RU', '{delta, plural, one{# месяц} few{# месяца} many{# месяцев} other{# месяцев}}', 0, 0),
    (25, 'uk-UA', '{delta, plural, one{# місяць} few{# місяця} many{# місяців} other{# місяців}}', 0, 0),
    (26, 'en-US', '{delta, plural, =1{1 day} other{# days}}', 0, 0),
    (26, 'ru-RU', '{delta, plural, one{# день} few{# дня} many{# дней} other{# дней}}', 0, 0),
    (26, 'uk-UA', '{delta, plural, one{# день} few{# дні} many{# днів} other{# днів}}', 0, 0),
    (27, 'en-US', '{delta, plural, =1{1 hour} other{# hours}}', 0, 0),
    (27, 'ru-RU', '{delta, plural, one{# час} few{# часа} many{# часов} other{# часов}}', 0, 0),
    (27, 'uk-UA', '{delta, plural, one{# година} few{# години} many{# годин} other{# годин}}', 0, 0),
    (28, 'en-US', '{delta, plural, =1{1 minute} other{# minutes}}', 0, 0),
    (28, 'ru-RU', '{delta, plural, one{# минута} few{# минуты} many{# минут} other{# минут}}', 0, 0),
    (28, 'uk-UA', '{delta, plural, one{# хвилина} few{# хвилини} many{# хвилин} other{# хвилин}}', 0, 0),
    (29, 'en-US', '{delta, plural, =1{1 second} other{# seconds}}', 0, 0),
    (29, 'ru-RU', '{delta, plural, one{# секунда} few{# секунды} many{# секунд} other{# секунд}}', 0, 0),
    (29, 'uk-UA', '{delta, plural, one{# секунда} few{# секунди} many{# секунд} other{# секунд}}', 0, 0),
    (30, 'en-US', '{nFormatted} B', 0, 0),
    (30, 'ru-RU', '{nFormatted} Б', 0, 0),
    (30, 'uk-UA', '{nFormatted} Б', 0, 0),
    (31, 'en-US', '{nFormatted} KiB', 0, 0),
    (31, 'ru-RU', '{nFormatted} КиБ', 0, 0),
    (31, 'uk-UA', '{nFormatted} КіБ', 0, 0),
    (32, 'en-US', '{nFormatted} MiB', 0, 0),
    (32, 'ru-RU', '{nFormatted} МиБ', 0, 0),
    (32, 'uk-UA', '{nFormatted} МіБ', 0, 0),
    (33, 'en-US', '{nFormatted} GiB', 0, 0),
    (33, 'ru-RU', '{nFormatted} ГиБ', 0, 0),
    (33, 'uk-UA', '{nFormatted} ГіБ', 0, 0),
    (34, 'en-US', '{nFormatted} TiB', 0, 0),
    (34, 'ru-RU', '{nFormatted} ТиБ', 0, 0),
    (34, 'uk-UA', '{nFormatted} ТіБ', 0, 0),
    (35, 'en-US', '{nFormatted} PiB', 0, 0),
    (35, 'ru-RU', '{nFormatted} ПиБ', 0, 0),
    (35, 'uk-UA', '{nFormatted} ПіБ', 0, 0),
    (36, 'en-US', '{nFormatted} KB', 0, 0),
    (36, 'ru-RU', '{nFormatted} КБ', 0, 0),
    (36, 'uk-UA', '{nFormatted} Кб', 0, 0),
    (37, 'en-US', '{nFormatted} MB', 0, 0),
    (37, 'ru-RU', '{nFormatted} МБ', 0, 0),
    (37, 'uk-UA', '{nFormatted} Мб', 0, 0),
    (38, 'en-US', '{nFormatted} GB', 0, 0),
    (38, 'ru-RU', '{nFormatted} ГБ', 0, 0),
    (38, 'uk-UA', '{nFormatted} Гб', 0, 0),
    (39, 'en-US', '{nFormatted} TB', 0, 0),
    (39, 'ru-RU', '{nFormatted} ТБ', 0, 0),
    (39, 'uk-UA', '{nFormatted} Тб', 0, 0),
    (40, 'en-US', '{nFormatted} PB', 0, 0),
    (40, 'ru-RU', '{nFormatted} ПБ', 0, 0),
    (40, 'uk-UA', '{nFormatted} Пб', 0, 0),
    (41, 'en-US', '{nFormatted} {n, plural, =1{byte} other{bytes}}', 0, 0),
    (41, 'ru-RU', '{nFormatted} {n, plural, one{байт} few{байта} many{байтов} other{байта}}', 0, 0),
    (41, 'uk-UA', '{nFormatted} {n, plural, one{байт} few{байта} many{байтів} other{байта}}', 0, 0),
    (42, 'en-US', '{nFormatted} {n, plural, =1{kibibyte} other{kibibytes}}', 0, 0),
    (42, 'ru-RU', '{nFormatted} {n, plural, one{кибибайт} few{кибибайта} many{кибибайтов} other{кибибайта}}', 0, 0),
    (42, 'uk-UA', '{nFormatted} {n, plural, one{кібібайт} few{кібібайта} many{кібібайтів} other{кібібайта}}', 0, 0),
    (43, 'en-US', '{nFormatted} {n, plural, =1{mebibyte} other{mebibytes}}', 0, 0),
    (43, 'ru-RU', '{nFormatted} {n, plural, one{мебибайт} few{мебибайта} many{мебибайтов} other{мебибайта}}', 0, 0),
    (43, 'uk-UA', '{nFormatted} {n, plural, one{мебібайт} few{мебібайта} many{мебібайтів} other{мебібайта}}', 0, 0),
    (44, 'en-US', '{nFormatted} {n, plural, =1{gibibyte} other{gibibytes}}', 0, 0),
    (44, 'ru-RU', '{nFormatted} {n, plural, one{гибибайт} few{гибибайта} many{гибибайтов} other{гибибайта}}', 0, 0),
    (44, 'uk-UA', '{nFormatted} {n, plural, one{гібібайт} few{гібібайта} many{гібібайтів} other{гібібайта}}', 0, 0),
    (45, 'en-US', '{nFormatted} {n, plural, =1{tebibyte} other{tebibytes}}', 0, 0),
    (45, 'ru-RU', '{nFormatted} {n, plural, one{тебибайт} few{тебибайта} many{тебибайтов} other{тебибайта}}', 0, 0),
    (45, 'uk-UA', '{nFormatted} {n, plural, one{тебібайт} few{тебібайта} many{тебібайтів} other{тебібайта}}', 0, 0),
    (46, 'en-US', '{nFormatted} {n, plural, =1{pebibyte} other{pebibytes}}', 0, 0),
    (46, 'ru-RU', '{nFormatted} {n, plural, one{пебибайт} few{пебибайта} many{пебибайтов} other{пебибайта}}', 0, 0),
    (46, 'uk-UA', '{nFormatted} {n, plural, one{пебібайт} few{пебібайта} many{пебібайтів} other{пебібайта}}', 0, 0),
    (47, 'en-US', '{nFormatted} {n, plural, =1{kilobyte} other{kilobytes}}', 0, 0),
    (47, 'ru-RU', '{nFormatted} {n, plural, one{килобайт} few{килобайта} many{килобайтов} other{килобайта}}', 0, 0),
    (47, 'uk-UA', '{nFormatted} {n, plural, one{кілобайт} few{кілобайта} many{кілобайтів} other{кілобайта}}', 0, 0),
    (48, 'en-US', '{nFormatted} {n, plural, =1{megabyte} other{megabytes}}', 0, 0),
    (48, 'ru-RU', '{nFormatted} {n, plural, one{мегабайт} few{мегабайта} many{мегабайтов} other{мегабайта}}', 0, 0),
    (48, 'uk-UA', '{nFormatted} {n, plural, one{мегабайт} few{мегабайта} many{мегабайтів} other{мегабайта}}', 0, 0),
    (49, 'en-US', '{nFormatted} {n, plural, =1{gigabyte} other{gigabytes}}', 0, 0),
    (49, 'ru-RU', '{nFormatted} {n, plural, one{гигабайт} few{гигабайта} many{гигабайтов} other{гигабайта}}', 0, 0),
    (49, 'uk-UA', '{nFormatted} {n, plural, one{гігабайт} few{гігабайта} many{гігабайтів} other{гігабайта}}', 0, 0),
    (50, 'en-US', '{nFormatted} {n, plural, =1{terabyte} other{terabytes}}', 0, 0),
    (50, 'ru-RU', '{nFormatted} {n, plural, one{терабайт} few{терабайта} many{терабайтов} other{терабайта}}', 0, 0),
    (50, 'uk-UA', '{nFormatted} {n, plural, one{терабайт} few{терабайта} many{терабайтів} other{терабайта}}', 0, 0),
    (51, 'en-US', '{nFormatted} {n, plural, =1{petabyte} other{petabytes}}', 0, 0),
    (51, 'ru-RU', '{nFormatted} {n, plural, one{петабайт} few{петабайта} many{петабайтов} other{петабайта}}', 0, 0),
    (51, 'uk-UA', '{nFormatted} {n, plural, one{петабайт} few{петабайта} many{петабайтів} other{петабайта}}', 0, 0),
    (52, 'en-US', 'You are not allowed to perform this action.', 0, 0),
    (52, 'ru-RU', 'Вам не разрешено производить данное действие.', 0, 0),
    (52, 'uk-UA', 'Вам не дозволено виконувати дану дію.', 0, 0),
    (53, 'en-US', 'Powered by {yii}', 0, 1481716945),
    (53, 'ru-RU', 'Powered by {yii}', 0, 1481716945),
    (53, 'uk-UA', 'Powered by {yii}', 0, 1481716945),
    (54, 'en-US', 'Yii Framework', 0, 1481716961),
    (54, 'ru-RU', 'Yii Framework', 0, 1481716961),
    (54, 'uk-UA', 'Yii Framework', 0, 1481716961),
    (55, 'en-US', 'Page not found.', 0, 0),
    (55, 'ru-RU', 'Страница не найдена.', 0, 0),
    (55, 'uk-UA', 'Сторінка не знайдена.', 0, 0),
    (56, 'en-US', 'Error', 0, 0),
    (56, 'ru-RU', 'Ошибка', 0, 0),
    (56, 'uk-UA', 'Помилка', 0, 0),
    (57, 'en-US', 'An internal server error occurred.', 0, 0),
    (57, 'ru-RU', 'Возникла внутренняя ошибка сервера.', 0, 0),
    (57, 'uk-UA', 'Виникла внутрішня помилка сервера.', 0, 0),
    (58, 'en-US', 'Login Required', 0, 0),
    (58, 'ru-RU', 'Требуется вход.', 0, 0),
    (58, 'uk-UA', 'Необхідно увійти', 0, 0),
    (59, 'en-US', 'The requested view "{name}" was not found.', 0, 0),
    (59, 'ru-RU', 'Запрашиваемый файл представления "{name}" не найден.', 0, 0),
    (59, 'uk-UA', 'Представлення "{name}" не знайдено.', 0, 0),
    (60, 'en-US', 'Invalid data received for parameter "{param}".', 0, 0),
    (60, 'ru-RU', 'Неправильное значение параметра "{param}".', 0, 0),
    (60, 'uk-UA', 'Отримано невірне значення для параметра "{param}".', 0, 0),
    (61, 'en-US', 'Missing required parameters: {params}', 0, 0),
    (61, 'ru-RU', 'Отсутствуют обязательные параметры: {params}', 0, 0),
    (61, 'uk-UA', 'Відсутні обовʼязкові параметри: {params}', 0, 0),
    (62, 'en-US', 'Unable to verify your data submission.', 0, 0),
    (62, 'ru-RU', 'Не удалось проверить переданные данные.', 0, 0),
    (62, 'uk-UA', 'Не вдалося перевірити передані дані.', 0, 0),
    (63, 'en-US', '{attribute} is invalid.', 0, 0),
    (63, 'ru-RU', 'Значение «{attribute}» неверно.', 0, 0),
    (63, 'uk-UA', 'Значення "{attribute}" не вірне.', 0, 0),
    (64, 'en-US', 'The combination {values} of {attributes} has already been taken.', 0, 1481716985),
    (64, 'ru-RU', 'The combination {values} of {attributes} has already been taken.', 0, 1481716985),
    (64, 'uk-UA', 'The combination {values} of {attributes} has already been taken.', 0, 1481716985),
    (65, 'en-US', '{attribute} "{value}" has already been taken.', 0, 0),
    (65, 'ru-RU', 'Значение «{value}» для «{attribute}» уже занято.', 0, 0),
    (65, 'uk-UA', 'Значення «{value}» для «{attribute}» вже зайнято.', 0, 0),
    (66, 'en-US', 'File upload failed.', 0, 0),
    (66, 'ru-RU', 'Загрузка файла не удалась.', 0, 0),
    (66, 'uk-UA', 'Завантаження файлу не вдалося.', 0, 0),
    (67, 'en-US', 'Please upload a file.', 0, 0),
    (67, 'ru-RU', 'Загрузите файл.', 0, 0),
    (67, 'uk-UA', 'Будь ласка, завантажте файл.', 0, 0),
    (68, 'en-US', 'You can upload at most {limit, number} {limit, plural, one{file} other{files}}.', 0, 0),
    (68, 'ru-RU', 'Вы не можете загружать более {limit, number} {limit, plural, one{файла} few{файлов} many{файлов} other{файла}}.', 0, 0),
    (68, 'uk-UA', 'Ви не можете завантажувати більше {limit, number} {limit, plural, one{файла} few{файлів} many{файлів} other{файла}}.', 0, 0),
    (69, 'en-US', 'Only files with these extensions are allowed: {extensions}.', 0, 0),
    (69, 'ru-RU', 'Разрешена загрузка файлов только со следующими расширениями: {extensions}.', 0, 0),
    (69, 'uk-UA', 'Дозволені файли лише з наступними розширеннями: {extensions}.', 0, 0),
    (70, 'en-US', 'The file "{file}" is too big. Its size cannot exceed {formattedLimit}.', 0, 0),
    (70, 'ru-RU', 'Файл «{file}» слишком большой. Размер не должен превышать {formattedLimit}.', 0, 0),
    (70, 'uk-UA', 'Файл "{file}" занадто великий. Розмір не повинен перевищувати {formattedLimit}.', 0, 0),
    (71, 'en-US', 'The file "{file}" is too small. Its size cannot be smaller than {formattedLimit}.', 0, 0),
    (71, 'ru-RU', 'Файл «{file}» слишком маленький. Размер должен быть более {formattedLimit}.', 0, 0),
    (71, 'uk-UA', 'Файл "{file}" занадто малий. Розмір повинен бути більше, ніж {formattedLimit}.', 0, 0),
    (72, 'en-US', 'Only files with these MIME types are allowed: {mimeTypes}.', 0, 0),
    (72, 'ru-RU', 'Разрешена загрузка файлов только со следующими MIME-типами: {mimeTypes}.', 0, 0),
    (72, 'uk-UA', 'Дозволені файли лише з наступними MIME-типами: {mimeTypes}.', 0, 0),
    (73, 'en-US', 'The format of {attribute} is invalid.', 0, 0),
    (73, 'ru-RU', 'Неверный формат значения «{attribute}».', 0, 0),
    (73, 'uk-UA', 'Невірний формат значення "{attribute}".', 0, 0),
    (74, 'en-US', '{attribute} must be no less than {min}.', 0, 0),
    (74, 'ru-RU', 'Значение «{attribute}» должно быть не меньше {min}.', 0, 0),
    (74, 'uk-UA', 'Значення "{attribute}" має бути більшим {min}.', 0, 0),
    (75, 'en-US', '{attribute} must be no greater than {max}.', 0, 0),
    (75, 'ru-RU', 'Значение «{attribute}» не должно превышать {max}.', 0, 0),
    (75, 'uk-UA', 'Значення "{attribute}" не повинно перевищувати {max}.', 0, 0),
    (76, 'en-US', '{attribute} must be equal to "{compareValueOrAttribute}".', 0, 0),
    (76, 'ru-RU', 'Значение «{attribute}» должно быть равно «{compareValueOrAttribute}».', 0, 0),
    (76, 'uk-UA', 'Значення "{attribute}" повинно бути рівним "{compareValueOrAttribute}".', 0, 0),
    (77, 'en-US', '{attribute} must not be equal to "{compareValueOrAttribute}".', 0, 0),
    (77, 'ru-RU', 'Значение «{attribute}» не должно быть равно «{compareValueOrAttribute}».', 0, 0),
    (77, 'uk-UA', 'Значення "{attribute}" не повинно бути рівним "{compareValueOrAttribute}".', 0, 0),
    (78, 'en-US', '{attribute} must be greater than "{compareValueOrAttribute}".', 0, 0),
    (78, 'ru-RU', 'Значение «{attribute}» должно быть больше значения «{compareValueOrAttribute}».', 0, 0),
    (78, 'uk-UA', 'Значення "{attribute}" повинно бути більшим значення "{compareValueOrAttribute}".', 0, 0),
    (79, 'en-US', '{attribute} must be greater than or equal to "{compareValueOrAttribute}".', 0, 0),
    (79, 'ru-RU', 'Значение «{attribute}» должно быть больше или равно значения «{compareValueOrAttribute}».', 0, 0),
    (79, 'uk-UA', 'Значення "{attribute}" повинно бути більшим або дорівнювати значенню "{compareValueOrAttribute}".', 0, 0),
    (80, 'en-US', '{attribute} must be less than "{compareValueOrAttribute}".', 0, 0),
    (80, 'ru-RU', 'Значение «{attribute}» должно быть меньше значения «{compareValueOrAttribute}».', 0, 0),
    (80, 'uk-UA', 'Значення "{attribute}" повинно бути меншим значення "{compareValueOrAttribute}".', 0, 0),
    (81, 'en-US', '{attribute} must be less than or equal to "{compareValueOrAttribute}".', 0, 0),
    (81, 'ru-RU', 'Значение «{attribute}» должно быть меньше или равно значения «{compareValueOrAttribute}».', 0, 0),
    (81, 'uk-UA', 'Значення "{attribute}" повинно бути меншим або дорівнювати значенню "{compareValueOrAttribute}".', 0, 0),
    (82, 'en-US', 'the input value', 0, 0),
    (82, 'ru-RU', 'введённое значение', 0, 0),
    (82, 'uk-UA', 'введене значення', 0, 0),
    (83, 'en-US', '{attribute} must be a string.', 0, 0),
    (83, 'ru-RU', 'Значение «{attribute}» должно быть строкой.', 0, 0),
    (83, 'uk-UA', 'Значення "{attribute}" має бути текстовим рядком.', 0, 0),
    (84, 'en-US', '{attribute} should contain at least {min, number} {min, plural, one{character} other{characters}}.', 0, 0),
    (84, 'ru-RU', 'Значение «{attribute}» должно содержать минимум {min, number} {min, plural, one{символ} few{символа} many{символов} other{символа}}.', 0, 0),
    (84, 'uk-UA', 'Значення "{attribute}" повинно містити мінімум {min, number} {min, plural, one{символ} few{символа} many{символів} other{символа}}.', 0, 0),
    (85, 'en-US', '{attribute} should contain at most {max, number} {max, plural, one{character} other{characters}}.', 0, 0),
    (85, 'ru-RU', 'Значение «{attribute}» должно содержать максимум {max, number} {max, plural, one{символ} few{символа} many{символов} other{символа}}.', 0, 0),
    (85, 'uk-UA', 'Значення "{attribute}" повинно містити максимум {max, number} {max, plural, one{символ} few{символа} many{символів} other{символа}}.', 0, 0),
    (86, 'en-US', '{attribute} should contain {length, number} {length, plural, one{character} other{characters}}.', 0, 0),
    (86, 'ru-RU', 'Значение «{attribute}» должно содержать {length, number} {length, plural, one{символ} few{символа} many{символов} other{символа}}.', 0, 0),
    (86, 'uk-UA', 'Значення "{attribute}" повинно містити {length, number} {length, plural, one{символ} few{символа} many{символів} other{символа}}.', 0, 0),
    (87, 'en-US', '{attribute} must be an integer.', 0, 0),
    (87, 'ru-RU', 'Значение «{attribute}» должно быть целым числом.', 0, 0),
    (87, 'uk-UA', 'Значення "{attribute}" має бути цілим числом.', 0, 0),
    (88, 'en-US', '{attribute} must be a number.', 0, 0),
    (88, 'ru-RU', 'Значение «{attribute}» должно быть числом.', 0, 0),
    (88, 'uk-UA', 'Значення "{attribute}" має бути числом.', 0, 0),
    (89, 'en-US', '{attribute} must be either "{true}" or "{false}".', 0, 0),
    (89, 'ru-RU', 'Значение «{attribute}» должно быть равно «{true}» или «{false}».', 0, 0),
    (89, 'uk-UA', 'Значення "{attribute}" має дорівнювати "{true}" або "{false}".', 0, 0),
    (90, 'en-US', '{attribute} is not a valid email address.', 0, 0),
    (90, 'ru-RU', 'Значение «{attribute}» не является правильным email адресом.', 0, 0),
    (90, 'uk-UA', 'Значення "{attribute}" не є правильною email адресою.', 0, 0),
    (91, 'en-US', '{attribute} is not a valid URL.', 0, 0),
    (91, 'ru-RU', 'Значение «{attribute}» не является правильным URL.', 0, 0),
    (91, 'uk-UA', 'Значення "{attribute}" не є правильним URL.', 0, 0),
    (92, 'en-US', '{attribute} cannot be blank.', 0, 0),
    (92, 'ru-RU', 'Необходимо заполнить «{attribute}».', 0, 0),
    (92, 'uk-UA', 'Необхідно заповнити "{attribute}".', 0, 0),
    (93, 'en-US', '{attribute} must be "{requiredValue}".', 0, 0),
    (93, 'ru-RU', 'Значение «{attribute}» должно быть равно «{requiredValue}».', 0, 0),
    (93, 'uk-UA', 'Значення "{attribute}" має бути рівним "{requiredValue}".', 0, 0),
    (94, 'en-US', 'The file "{file}" is not an image.', 0, 0),
    (94, 'ru-RU', 'Файл «{file}» не является изображением.', 0, 0),
    (94, 'uk-UA', 'Файл "{file}" не є зображенням.', 0, 0),
    (95, 'en-US', 'The image "{file}" is too small. The width cannot be smaller than {limit, number} {limit, plural, one{pixel} other{pixels}}.', 0, 0),
    (95, 'ru-RU', 'Файл «{file}» слишком маленький. Ширина должна быть более {limit, number} {limit, plural, one{пиксель} few{пикселя} many{пикселей} other{пикселя}}.', 0, 0),
    (95, 'uk-UA', 'Зображення "{file}" занадто мале. Ширина повинна бути більше, ніж {limit, number} {limit, plural, one{піксель} few{пікселя} many{пікселів} other{пікселя}}.', 0, 0),
    (96, 'en-US', 'The image "{file}" is too small. The height cannot be smaller than {limit, number} {limit, plural, one{pixel} other{pixels}}.', 0, 0),
    (96, 'ru-RU', 'Файл «{file}» слишком маленький. Высота должна быть более {limit, number} {limit, plural, one{пиксель} few{пикселя} many{пикселей} other{пикселя}}.', 0, 0),
    (96, 'uk-UA', 'Зображення "{file}" занадто мале. Висота повинна бути більше, ніж {limit, number} {limit, plural, one{піксель} few{пікселя} many{пікселів} other{пікселя}}.', 0, 0),
    (97, 'en-US', 'The image "{file}" is too large. The width cannot be larger than {limit, number} {limit, plural, one{pixel} other{pixels}}.', 0, 0),
    (97, 'ru-RU', 'Файл «{file}» слишком большой. Ширина не должна превышать {limit, number} {limit, plural, one{пиксель} few{пикселя} many{пикселей} other{пикселя}}.', 0, 0),
    (97, 'uk-UA', 'Зображення "{file}" занадто велике. Ширина не повинна перевищувати {limit, number} {limit, plural, one{піксель} few{пікселя} many{пікселів} other{пікселя}}.', 0, 0),
    (98, 'en-US', 'The image "{file}" is too large. The height cannot be larger than {limit, number} {limit, plural, one{pixel} other{pixels}}.', 0, 0),
    (98, 'ru-RU', 'Файл «{file}» слишком большой. Высота не должна превышать {limit, number} {limit, plural, one{пиксель} few{пикселя} many{пикселей} other{пикселя}}.', 0, 0),
    (98, 'uk-UA', 'Зображення "{file}" занадто велике. Висота не повинна перевищувати {limit, number} {limit, plural, one{піксель} few{пікселя} many{пікселів} other{пікселя}}.', 0, 0),
    (99, 'en-US', '{attribute} must be a valid IP address.', 0, 0),
    (99, 'ru-RU', 'Значение «{attribute}» должно быть правильным IP адресом.', 0, 0),
    (99, 'uk-UA', 'Значення «{attribute}» повинно бути правильною IP адресою.', 0, 0),
    (100, 'en-US', '{attribute} must not be an IPv6 address.', 0, 0),
    (100, 'ru-RU', 'Значение «{attribute}» не должно быть IPv6 адресом.', 0, 0),
    (100, 'uk-UA', 'Значення «{attribute}» не повинно бути IPv6 адресою.', 0, 0),
    (101, 'en-US', '{attribute} must not be an IPv4 address.', 0, 0),
    (101, 'ru-RU', 'Значение «{attribute}» не должно быть IPv4 адресом.', 0, 0),
    (101, 'uk-UA', 'Значення «{attribute}» не повинно бути IPv4 адресою.', 0, 0),
    (102, 'en-US', '{attribute} contains wrong subnet mask.', 0, 0),
    (102, 'ru-RU', 'Значение «{attribute}» содержит неверную маску подсети.', 0, 0),
    (102, 'uk-UA', 'Значення «{attribute}» містить неправильну маску підмережі.', 0, 0),
    (103, 'en-US', '{attribute} must be an IP address with specified subnet.', 0, 0),
    (103, 'ru-RU', 'Значение «{attribute}» должно быть IP адресом с подсетью.', 0, 0),
    (103, 'uk-UA', 'Значення «{attribute}» повинно бути IP адресою з підмережею.', 0, 0),
    (104, 'en-US', '{attribute} must not be a subnet.', 0, 0),
    (104, 'ru-RU', 'Значение «{attribute}» не должно быть подсетью.', 0, 0),
    (104, 'uk-UA', 'Значення «{attribute}» не повинно бути підмережею.', 0, 0),
    (105, 'en-US', '{attribute} is not in the allowed range.', 0, 0),
    (105, 'ru-RU', 'Значение «{attribute}» не входит в список разрешенных диапазонов адресов.', 0, 0),
    (105, 'uk-UA', 'Значення «{attribute}» не входить в список дозволених діапазонів адрес.', 0, 0),
    (106, 'en-US', 'The verification code is incorrect.', 0, 0),
    (106, 'ru-RU', 'Неправильный проверочный код.', 0, 0),
    (106, 'uk-UA', 'Невірний код перевірки.', 0, 0),
    (107, 'en-US', 'View', 0, 0),
    (107, 'ru-RU', 'Просмотр', 0, 0),
    (107, 'uk-UA', 'Переглянути', 0, 0),
    (108, 'en-US', 'Update', 0, 0),
    (108, 'ru-RU', 'Редактировать', 0, 0),
    (108, 'uk-UA', 'Оновити', 0, 0),
    (109, 'en-US', 'Delete', 0, 0),
    (109, 'ru-RU', 'Удалить', 0, 0),
    (109, 'uk-UA', 'Видалити', 0, 0),
    (110, 'en-US', 'Are you sure you want to delete this item?', 0, 0),
    (110, 'ru-RU', 'Вы уверены, что хотите удалить этот элемент?', 0, 0),
    (110, 'uk-UA', 'Ви впевнені, що хочете видалити цей елемент?', 0, 0),
    (111, 'en-US', 'Please fix the following errors:', 0, 0),
    (111, 'ru-RU', 'Исправьте следующие ошибки:', 0, 0),
    (111, 'uk-UA', 'Будь ласка, виправте наступні помилки:', 0, 0),
    (112, 'en-US', '{percent}% Complete', 0, 1481717028),
    (112, 'ru-RU', '{percent}% Выполнено', 0, 1481717028),
    (112, 'uk-UA', '{percent}% Виконано', 0, 1481717028),
    (113, 'en-US', 'Update translation', 0, 1481715219),
    (113, 'ru-RU', 'Изменить перевод', 0, 1481715219),
    (113, 'uk-UA', 'Змінити перевод', 0, 1481715219),
    (114, 'en-US', 'Interface translations', 0, 1481715309),
    (114, 'ru-RU', 'Переводы интерфейса', 0, 1481715309),
    (114, 'uk-UA', 'Переклади інтерфейса', 0, 1481715309),
    (115, 'en-US', 'Create', 0, 1481715325),
    (115, 'ru-RU', 'Создать', 0, 1481715325),
    (115, 'uk-UA', 'Створити', 0, 1481715325),
    (116, 'en-US', 'Update', 0, 1481715340),
    (116, 'ru-RU', 'Обновить', 0, 1481715340),
    (116, 'uk-UA', 'Оновити', 0, 1481715340),
    (117, 'en-US', 'Translation ({language})', 0, 1481715363),
    (117, 'ru-RU', 'Перевод ({language})', 0, 1481715363),
    (117, 'uk-UA', 'Переклад ({language})', 0, 1481715363),
    (118, 'en-US', 'Add language', 0, 1481715388),
    (118, 'ru-RU', 'Добавить язык', 0, 1481715388),
    (118, 'uk-UA', 'Додати мову', 0, 1481715388),
    (119, 'en-US', 'Languages', 0, 1481715472),
    (119, 'ru-RU', 'Языки', 0, 1481715472),
    (119, 'uk-UA', 'Мови', 0, 1481715472),
    (120, 'en-US', 'Update language:', 0, 1481715560),
    (120, 'ru-RU', 'Изменение языка:', 0, 1481715560),
    (120, 'uk-UA', 'Зміна мови:', 0, 1481715560),
    (121, 'en-US', 'If you select this option here, it will be reset everywhere', 0, 1481715684),
    (121, 'ru-RU', 'Если Вы выберете данную опцию здесь, она будет сброшена везде', 0, 1481715684),
    (121, 'uk-UA', 'Якщо Ви виберете цю опцію тут, вона буде скинута всюди', 0, 1481715684),
    (122, 'en-US', 'Update language', 0, 1481715754),
    (122, 'ru-RU', 'Изменение языка', 0, 1481715754),
    (122, 'uk-UA', 'Оновлення мови', 0, 1481715754),
    (123, 'en-US', 'The combination of ID and Language has already been taken.', 0, 1481715821),
    (123, 'ru-RU', 'Данное сочетание ID и языка уже существует', 0, 1481715821),
    (123, 'uk-UA', 'Дане поєднання ID і мови вже існує', 0, 1481715821),
    (124, 'en-US', 'ID', 0, 1481715829),
    (124, 'ru-RU', 'ID', 0, 1481715829),
    (124, 'uk-UA', 'ID', 0, 1481715829),
    (125, 'en-US', 'Language', 0, 1481715843),
    (125, 'ru-RU', 'Язык', 0, 1481715843),
    (125, 'uk-UA', 'Мова', 0, 1481715843),
    (126, 'en-US', 'Translation', 0, 1481715861),
    (126, 'ru-RU', 'Перевод', 0, 1481715861),
    (126, 'uk-UA', 'Переклад', 0, 1481715861),
    (127, 'en-US', 'You can only override the default language', 0, 1481715922),
    (127, 'ru-RU', 'Вы можете только изменить язык установленный по умолчанию', 0, 1481715922),
    (127, 'uk-UA', 'Ви можете тільки змінити мову встановлену за замовчуванням', 0, 1481715922),
    (128, 'en-US', 'Url (ISO 639-1)', 0, 1481715934),
    (128, 'ru-RU', 'Url (ISO 639-1)', 0, 1481715934),
    (128, 'uk-UA', 'Url (ISO 639-1)', 0, 1481715934),
    (129, 'en-US', 'Locale', 0, 1481715998),
    (129, 'ru-RU', 'Локаль', 0, 1481715998),
    (129, 'uk-UA', 'Локаль', 0, 1481715998),
    (130, 'en-US', 'Name', 0, 1481716011),
    (130, 'ru-RU', 'Название', 0, 1481716011),
    (130, 'uk-UA', 'Назва', 0, 1481716011),
    (131, 'en-US', 'Is Default', 0, 1481716041),
    (131, 'ru-RU', 'По умолчанию', 0, 1481716041),
    (131, 'uk-UA', 'За замовчуванням', 0, 1481716041),
    (132, 'en-US', 'Created At', 0, 1481716055),
    (132, 'ru-RU', 'Создано', 0, 1481716055),
    (132, 'uk-UA', 'Створено', 0, 1481716055),
    (133, 'en-US', 'Updated At', 0, 1481716065),
    (133, 'ru-RU', 'Обновлено', 0, 1481716065),
    (133, 'uk-UA', 'Оновлено', 0, 1481716065),
    (134, 'en-US', 'Message category', 0, 1481716102),
    (134, 'ru-RU', 'Категория перевода', 0, 1481716102),
    (134, 'uk-UA', 'Категорія перекладу', 0, 1481716102),
    (135, 'en-US', 'Message key', 0, 1481716137),
    (135, 'ru-RU', 'Ключ перевода', 0, 1481716137),
    (135, 'uk-UA', 'Ключ перекладу', 0, 1481716137),
    (136, 'en-US', 'The requested translation does not exist', 0, 1481716193),
    (136, 'ru-RU', 'Запрашиваемый перевод не существует', 0, 1481716193),
    (136, 'uk-UA', 'Запитуваний переклад не існує', 0, 1481716193),
    (137, 'en-US', 'Translation updated successfully!', 0, 1481716235),
    (137, 'ru-RU', 'Перевод успешно изменен!', 0, 1481716235),
    (137, 'uk-UA', 'Переклад змінено успішно!', 0, 1481716235),
    (138, 'en-US', 'The requested language does not exist', 0, 1481716273),
    (138, 'ru-RU', 'Запрашиваемый язык не существует', 0, 1481716273),
    (138, 'uk-UA', 'Запитувана мова не існує', 0, 1481716273),
    (139, 'en-US', 'You can''t delete default language!', 0, 1481716305),
    (139, 'ru-RU', 'Вы не можете удалить язык по умолчанию!', 0, 1481716305),
    (139, 'uk-UA', 'Ви не можете видалити мову за замовчуванням!', 0, 1481716305),
    (140, 'en-US', 'Language deleted successfully!', 0, 1481716335),
    (140, 'ru-RU', 'Язык удален успешно!', 0, 1481716335),
    (140, 'uk-UA', 'Мову видалено успішно!', 0, 1481716335),
    (141, 'en-US', 'Language updated successfully!', 0, 1481716366),
    (141, 'ru-RU', 'Язык изменен успешно!', 0, 1481716366),
    (141, 'uk-UA', 'Мова змінена успішно!', 0, 1481716366),
    (142, 'en-US', 'Language created successfully!', 0, 1481716400),
    (142, 'ru-RU', 'Язык создан успешно!', 0, 1481716400),
    (142, 'uk-UA', 'Мова створена успішно!', 0, 1481716400),
    (143, 'en-US', 'Русский', 0, 1481716456),
    (143, 'ru-RU', 'Русский', 0, 1481716443),
    (143, 'uk-UA', 'Русский', 0, 1481716456),
    (144, 'en-US', 'Українська', 0, 1481716463),
    (144, 'ru-RU', 'Українська', 0, 1481716462),
    (144, 'uk-UA', 'Українська', 0, 1481716463),
    (145, 'en-US', 'English', 0, 1481716471),
    (145, 'ru-RU', 'English', 0, 1481716471),
    (145, 'uk-UA', 'English', 0, 1481716471);
SQL
        );
    }

    public function down()
    {
        Yii::$app->multilangCache->flush();
        if (Yii::$app->db->schema->getTableSchema(Message::TABLE_NAME) !== NULL) {
            $this->dropTable(Message::TABLE_NAME);
        }
        if (Yii::$app->db->schema->getTableSchema(SourceMessage::TABLE_NAME) !== NULL) {
            $this->dropTable(SourceMessage::TABLE_NAME);
        }
        if (Yii::$app->db->schema->getTableSchema(Language::TABLE_NAME) !== NULL) {
            $this->dropTable(Language::TABLE_NAME);
        }
    }
}
